### ISSUE TITLE
Feature Request: Keyboard shortcut to format SQL query using %%sql

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1006]
It would be interesting to have a keyboard shortcut in Datalab that will automatically format a SQL query in a cell. The keyboard shortcut could be enabled if the cell contains the Datalab magic command `%%sql`. 

As an example: On https://bigquery.cloud.google.com, users can automatically format their SQL query by using the keyboard shortcut `CTRL + SHIFT + F` .

**Comment by qimingj** [comment]
That's a great idea! Are on on it Tony? If not I can work on it.

**Comment by parthea** [comment]
Thanks @qimingj! It would be great if you could implement this!  I was really missing this feature after having used it in the Big Query UI. I would be happy to help with testing and code review for this feature.

**Comment by chmeyers** [comment]
@qimingj, have you done any work on this?  If not, I'm going to open it up for pull requests.

**Comment by nikhilk** [comment]
We should have a general format cell gesture/command that the SQL one plugs
into...

**Comment by qimingj** [comment]
Not yet.

**Comment by MichaelTheBrute** [comment]
I was hoping to migrate the code used at https://bigquery.cloud.google.com, but it appears to be custom code specifically written for the BigQuery Web UI.  See [gist](https://gist.github.com/MichaelTheBrute/4510e9ded8696552d659a732f5c63156).

Are you guys open to integrating something like this?

https://github.com/zeroturnaround/sql-formatter

**Comment by yebrahim** [comment]
Do you know if that code is legacy or standard SQL compliant, or both? Datalab is moving toward supporting only standard SQL. (You can take a look at the [migration guide](https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql) if you want to manual check.

**Comment by yebrahim** [comment]
Also, the magic that should be considered for potentially supporting this should now be `%%bq`, `%%sql` is being deprecated.

**Comment by MichaelTheBrute** [comment]
According to the docs, this system appears to support Standard SQL out of the box,

> ![image](https://user-images.githubusercontent.com/14703692/32806986-4f5b835e-c943-11e7-907d-da2068de60cd.png).

That said, having taken a high-level tour of the code it appears the system is designed to support configurable, plug-in like dialects; similar in spirit to CodeMirror modes.  So any bugs or incompatibilities should be easy enough to address. 

Worth taking a crack?

**Comment by qimingj** [comment]
Yes. I am looking into this. Unless someone else wants to take it, I am on it.

**Comment by MichaelTheBrute** [comment]
I'm not trying to stomp on your efforts here.  I checked out your profile and it looked like you were occupied with some other efforts, but I'll leave it with you and find something else.  :) 

Thanks!

**Comment by parthea** [comment]
Closing as obsolete.
