### ISSUE TITLE
Warning message in browser console: "Notebook.move_cell_up is deprecated"

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1007]
I noticed the following warnings in the browser console when using the "Move Up" and "Move Down" buttons inside a notebook:
- `Notebook.move_cell_up is deprecated as of v4.1 and will be removed in v5.0`
- `Notebook.move_cell_down is deprecated as of v4.1 and will be removed in v5.0`

![warningmessageinbrowserconsole](https://cloud.githubusercontent.com/assets/5184014/19208468/322cb478-8cc8-11e6-8daa-7294a35dad89.png)

**Comment by yebrahim** [comment]
I'm not sure it's useful to track this on our side. There [was talk](https://github.com/jupyter/notebook/issues/793) about it getting cut in Jupyter 5.0 at some point but I don't see it happening yet, I think it's a very important feature. I'll close this one for now since it's a no-op for Datalab.
