### ISSUE TITLE
Update ipywidgets to 5.1.5 or newer

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1012]
In https://github.com/googledatalab/datalab/blob/master/containers/base/Dockerfile#L67, I see Datalab uses ipywidgets 5.0.0 . 

On http://blog.jupyter.org/, there is a post recommending that users update to ipywidgets 5.1.5 or newer for security reasons (see http://blog.jupyter.org/2016/09/26/ipywidget-security-release/)

**Comment by qimingj** [comment]
I thought widgets are broken and not enabled in Datalab? We may need to fix it first.
