### ISSUE TITLE
Improve the edit page layout

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/datalab#1024]
This is the edit page for vanilla text files.

The edit page for that has some scroll issues (we applied our chrome, but probably need to update the default layout of the page) and as a nice-to-have also have line numbers in the editor.

**Comment by techtonik** [comment]
Where is it? Screens would be nice too.

**Comment by yebrahim** [comment]
![image](https://cloud.githubusercontent.com/assets/1424661/19497567/c4ba4540-9541-11e6-96ca-68287791fbc0.png)

There are at least three things wrong with this picture:
- No line numbers in the gutter
- Two scrollbars
- Extra scrolable space at the top and bottom of page
