### ISSUE TITLE
Notebook code editing improvements

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/datalab#1033]
A few improvements that will go a long way.
1. Current line highlighting
2. Double click identifier to show all occurrences of identifier in the notebook.

Presentation mode enhancements (possibly):
1. Selection bolding

**Comment by umang-sh** [comment]
Hi @nikhilk  
How do you plan to go ahead with it?
Going the lexical analysis ,parser way of code highlighting as they do in IDEs or changes in the typescript .
Correct me if I got the problem wrong 
This seems interesting to me ,need help starting this up :)

**Comment by yebrahim** [comment]
I think there are some Jupyter extensions that might do current line highlighting and double click highlighting, perhaps we can get these integrated in Datalab.

**Comment by umang-sh** [comment]
Hi Guys ,

We can use this https://github.com/jcb91/jupyter_highlight_selected_word for highlighting all the instances of a word.
This would need changes in the DockerFile.
Let  me know your thoughts regarding using this

**Comment by umang-sh** [comment]
Hi Guys,
@nikhilk @yebrahim @ojarjur 
I have addressed the word highlighting issue by adding the jupyter word highlighter extension 
More details on the same at the PR below
https://github.com/googledatalab/datalab/pull/2033
