### ISSUE TITLE
Support for themes / built in dark theme

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#104]
This is definitely post-alpha and could be post-beta. An intangible delighter to create a more emotional attachment to the tool and the experience of using it. In particular, a sizeable segment prefers dark themes. Sublime Text is a great example that defaults to such a theme and gets a lot of mileage out of it. 

See http://www.damian.oquanta.info/posts/48-themes-for-your-ipython-notebook.html for some work that has been done.

**Comment by yebrahim** [comment]
Fixed via #981.
