### ISSUE TITLE
The jupyter notebook have no button to stop a running cell.

### ISSUE THREAD

**Issue by soerendip** [googledatalab/datalab#1049]
Hi,
I cannot find a button to stop a cell in the jupyter notebooks in the datalab. Is that done on purpose?
I tried to install software with a %%bash magic function. But the script is interactive and needs input from stdin. The only way to stop the cell is to reset the whole notebook it seems. Usually ipython notebooks have a button to stop running cells without resetting the notebook.

**Comment by dovy** [comment]
+1
