### ISSUE TITLE
Feature Request: Add ability to search and navigate to a specific notebook

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1051]
It would be interesting to have a search text box in Datalab to help navigate to specific notebooks when the directory structure is very deep (lot's of clicking!). 

I am imagining a text box with autocomplete functionality. If I type in part of a notebook name, the autocomplete dropdown menu will show me notebooks that match my search pattern. Clicking on the autocomplete item would navigate to the corresponding notebook.

This is just a suggestion! Please feel free to close this issue if this is not helpful.

**Comment by VelizarVESSELINOV** [comment]
Today using GitHub to search to find a specific file or content inside the ipynb files, the power of Google search is missing inside Datalab.
