### ISSUE TITLE
Write failed: Broken pipe

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#1054]
Very often the Datalab stop working and the `Write failed: Broken pipe` error appears in my Kitematic logs window, even if the Internet connection is stable.

**Comment by yebrahim** [comment]
Are you running Datalab on GCE with SSH? Does this happen after long periods of inactivity?

**Comment by VelizarVESSELINOV** [comment]
Running Datalab in hybrid mode with VM on the GCP side (docker version with kernel gateway on GCE).
I would say more heavy usage more than inactivity. When there is a lot of data movement, computations, plotting. My prediction is more that reaching some saturation of the communication pipeline rather than inactivity.

**Comment by VelizarVESSELINOV** [comment]
Confirm as well the inactivity `broken pipe`, today more than 8 times restarted the Docker container.
6 times for `broken pipe` and 2 times for `Connection to x.x.x.x closed by remote host.`

**Comment by dovy** [comment]
Same

**Comment by VelizarVESSELINOV** [comment]
Any progress on this item, this bug is really annoying?

**Comment by moczkowski** [comment]
I still see this, too. As mentioned in #1116 the notebook itself shows no indicator of this so when you issue a command the status bar just shows forever with nothing really happening.

**Comment by jiajiayb** [comment]
same happens to me. when I am applying beam pipeline to read in huge files, it says 'running' forever and then says 'broken pipe'. I have to repeat the entire painful process again, and have no idea how long it will take.

**Comment by VelizarVESSELINOV** [comment]
With the latest version, don't need to restart Kitematic docker, changing network as well. Which is very good.

```
Write failed: Broken pipe
Restarting SSH tunnel
```

But still no visual indication on the UI is still in 'Running...' mode and it is unclear if it is because it is really running or the backend restarted, so no need to wait.
Please add a visual indication that the connection is broken and computation should be restarted.

**Comment by jiajiayb** [comment]
agree, a processing bar for 'running' could be very helpful. In my case, the broken pipe interrupted the ongoing computation. The restarted connection to server seems like do not resume the interrupted computation.

**Comment by ojarjur** [comment]
I'm going to close this as now being obsolete.

We've deprecated the hybrid mode so we don't have any plans to improve the story here over what we already had.
