### ISSUE TITLE
Datalab erroneously redirecting to '/login'

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1073]
We found this during our attempt at releasing today and had to rollback the release because of it.

Bradley is investigating to identify the root cause.

**Comment by qimingj** [comment]
It seems not related to any check-ins. the daily builds before (including) 12/8 work well. 12/9 build is screwed and we don't have checkins in datalab (and one unrelated checkin in pydatalab).

It seems more likely that apt-get update or some packages that we do not specify version got updated within 24 hours and datalab docker build picked it up. This is nasty and I have to dig further.

**Comment by qimingj** [comment]
Found the diff between 12/8 and 12/9 image. On 12/8, notebook = 4.2.3. On 12/9, notebook = 4.3.0. From log:
...
Collecting notebook>=4.2.0 (from widgetsnbextension>=1.2.6->ipywidgets==5.2.2)
  Downloading notebook-4.3.0-py2.py3-none-any.whl (6.9MB)
...
We probably need to pin notebook = 4.2.3.

**Comment by yebrahim** [comment]
It already is. It's getting updated by ipywidgets. We should find an ipywidgets version that doesn't require updating notebook.

**Comment by yebrahim** [comment]
Looks like this PR is what broke it: https://github.com/jupyter/notebook/pull/1831. I'll see if it's an easy fix.

**Comment by qimingj** [comment]
Thanks for chasing it down!
