### ISSUE TITLE
Sporadic request failures when using ungit via the reverse proxy

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1074]
When opening ungit via the Datalab UI (hence, when it is running behind the reverse proxy), requests frequently fail with 'ERR_CONTENT_LENGTH_MISMATCH' error messages (as reported by the browser).

This is not reproducible if I connect directly to ungit (e.g. by mapping some local port to port 8083 in the container), so it seems to be related to the traffic going through the reverse proxy.

I have not yet tested to see if this is limited to ungit or if TensorBoard also has the same issue.

**Comment by ojarjur** [comment]
@yebrahim @qimingj If either of you have any ideas on what could be happening here, then please let me know.

**Comment by qimingj** [comment]
Add logging on this line https://github.com/googledatalab/datalab/blob/master/sources/web/datalab/reverseProxy.ts#L27 and turn on datalab debugging?

**Comment by ojarjur** [comment]
@qimingj I actually tried that and nothing wound up being logged, so the error handler wasn't being invoked.

**Comment by qimingj** [comment]
Anything from the console or network in chrome developer developer tools?

**Comment by yebrahim** [comment]
I'm not seeing these errors in the dev tools. The only thing I see there is one failure about refreshButton.css not loading.

**Comment by ojarjur** [comment]
I tracked this down to being the result of me chaining together multiple levels of SSH tunnel (SSH tunnel from a VM to my computer, and then from my compute to a Chromebook).

I was not able to reproduce the issue in any other environment, so it seems to simply have been the result of my convoluted setup.
