### ISSUE TITLE
Support bq-style short references in the datalab.py tool

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1089]
The `bq` command line tool for BigQuery supports specifying the project ID and dataset for a table as part of the positional argument specifying that table.

For instance, "project_id:dataset.table" can be used to specify the table "table" in the dataset "dataset" in the project "project_id".

We may want to add something similar for referring to the project and zone of a Datalab instance.

e.g. "my-project:us-central1-a.my-instance" instead of "--project my-project --zone us-central1-a my-instance".

This would apply to every command.

**Comment by chmeyers** [comment]
I believe we ended up following gcloud conventions for the datalab tool, which requires the separate flags.  Please reopen if you think we'll still make this change in the future.
