### ISSUE TITLE
how to read in large csv or npy (numpy array) files from google storage

### ISSUE THREAD

**Issue by jiajiayb** [googledatalab/datalab#1102]
Hi, please bear with my dumb question. I am pretty new to datalab and google cloud platform. The question I have right now is, I have my datasets stored in google storage, and I will like to apply deep learning to those datasets using datalab. I have tried tensorflow in my local computer and it works fine on small dataset. The goal is to apply the same code to larger dataset in google cloud platform since it is not doable in my local computer. I realized that it is not possible to read in csv or npy files in datalab by using pd.read_table() or np.load(). I just wonder if there is a simple example you could provide how to read in the csv or npy from google storage and then treat the table as the pandas or numpy variable just like what I did in my local computer. Thanks a lot for your help and time in advance!

**Comment by qimingj** [comment]
pandas DataFrame is in memory so you cannot load data with DataFrame for large datasets.

You can create a TensorFlow model that reads csv data in batches so it never needs to load all data in memory. Check the Iris machine learning sample in Datalab under docs/tutorials for an end to end solution example.

Also, check out https://www.tensorflow.org/how_tos/reading_data/#reading-from-files on TensorFlow's csv reader.
