### ISSUE TITLE
Gateway: Timeout after inactivity

### ISSUE THREAD

**Issue by dovy** [googledatalab/datalab#1116]
After long inactivity the system will take a moment to reconnect to the UI, but it will never execute a command to the spark cluster again. The docker file must be closed and a new session must be established. Would like a visual feedback when this occurs.

**Comment by dovy** [comment]
Same issue as #1114 occurs. Must make a new cluster to reconnect. Boo.

**Comment by moczkowski** [comment]
Is this a duplicate of #1054?

**Comment by dovy** [comment]
Correct. Closing.
