### ISSUE TITLE
build.sh: rsync needs a trailing slash

### ISSUE THREAD

**Issue by brandondutra** [googledatalab/datalab#1118]
In datalab/containers/base/build.sh, the line 

rsync -avp "$1" pydatalab

does not work if $1 is a path that does NOT end in '/'. "rsync -avp test pydatalab" will put the folder test under pydatalab, which is not what we want.  "rsync -avp test/ pydatalab" will put the contents of test into pydatalab, which is desired.

**Comment by qimingj** [comment]
Indeed. It seems rsync does not handle that well? I always put '/' after the path by auto completion so never hit this before.

**Comment by brandondutra** [comment]
Pull request #1119 fixed this.
