### ISSUE TITLE
Ungit gives a Connection Lost error

### ISSUE THREAD

**Issue by yebrahim** [googledatalab/datalab#1125]
Ungit no longer loads:

![image](https://cloud.githubusercontent.com/assets/1424661/21960439/97bacb92-daa0-11e6-8946-17423f21e99d.png)

**Comment by yebrahim** [comment]
@ojarjur looks like [this](https://github.com/googledatalab/datalab/commit/e781b3fb5a47aac2bf11a82a8905197d00b821a1#diff-871b92ed67fb026c8a67059958abc8eaR293) call to `wrapServer` is causing ungit to not load, could you take a look?

**Comment by ojarjur** [comment]
@yebrahim It does seem that the two socket.io wrappers (the one in Datalab and the one in ungit) are conflicting.

I'll figure out how to make them work together.
