### ISSUE TITLE
Add endpoints with kernel gateway to Datalab

### ISSUE THREAD

**Issue by eeveeta** [googledatalab/datalab#1146]
We are working on a project that relies on Jupyter notebooks using kernel gateway endpoints to make HTTP requests to it. Adding all the Datalab capabilities would tremendously improve our project, but we need to keep the endpoints live. It would be very helpful if you added kernel gateway compatibility to Datalab.

**Comment by chmeyers** [comment]
I'm not sure what is needed here.  Datalab has Kernel Gateways support, though it requires a separate docker container.

**Comment by ojarjur** [comment]
Some more background is [here](http://stackoverflow.com/questions/41818467/can-i-create-kernel-gateway-endpoints-in-google-cloud-datalab).

In short, the request is to be able to run a notebook as an application.

The simplest way for us to support that is to make our "gcr.io/cloud-datalab/datalab:gateway" image support some sort of a "NOTEBOOK=..." environment variable, and then use that to add the following flags to the `jupyter kernelgateway` command:

1. "--KernelGatewayApp.api=kernel_gateway.notebook_http"
2. "--KernelGatewayApp.seed_uri=<YOUR NOTEBOOK>"
