### ISSUE TITLE
Configure swap space on GCE VM to reduce OOM probability

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#1161]
The current default n1-standard-1 VM has modest memory when compared to recent workstations and even laptops. Those who routinely use large datasets are probably better off with a highmem machine-type but for most other users, it is better to experience some slowdown on larger analyses than run into OOM and being forced to create another instance. 

It looks like it is better to configure swap space on the VM itself to avoid complications around doing it from a container. 

[This link](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s2-diskpartrecommend-ppc.html#id4394007) has some suggestions about swap space size though our mileage may vary.

**Comment by nikhilk** [comment]
From a quick glance, it seems we should have the same amount of swap space as memory in the VM. Is this something that should be done on the host VM, or something in the container as well?

Finally, we should perhaps think about showing CPU/memory utilization in the "datalab info" command.

**Comment by Di-Ku** [comment]
I haven't tried these parm in general and certainly not on GCI but these two pointers are interesting:
Basic command ref for how to run the container: https://docs.docker.com/engine/reference/run/
Thread indicating that host should be set up with appropriate swap space: https://forums.docker.com/t/docker-swap-space/3908/3
