### ISSUE TITLE
Please alpha test the GA preview release

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#1177]
[This](https://github.com/googledatalab/datalab/wiki/Release-Info#222017---v0520170202---pre-ga-preview-release) non-mainline release on the path to GA fixes a number of issues with connectivity and use of kernel gateways. The command line tool has streamlined deployment and the core functionality for using git (via Cloud Source Repositories) and having notebooks backed up is in place.

Please use this issue to report bugs and other problems or questions.

**Comment by dovy** [comment]
Fantastic work, the connectivity issues are resolved in the gateway mode as well as 100% remote. I commend you all.
