### ISSUE TITLE
Chart doesn't work on the GA preview release

### ISSUE THREAD

**Issue by kazunori279** [googledatalab/datalab#1185]
I'm running Datalab instance of GCE instance created with the new CLI. The chart examples on Readme doesn't work at all.

**Comment by nikhilk** [comment]
Hi Kaz ... a few questions.
- Which specific chart and/or notebook was not working?
- Are you running the CLI commands in a cloud shell, or locally? Some geocharts require the browser to be on http://localhost.

**Comment by kazunori279** [comment]
Hi Nikhil, sorry for slow response.

- The entire chart sample notebook didn't work
- I'm running Datalab locally with Docker

**Comment by yebrahim** [comment]
@kazunori279 can you share more info on the failure? Is "Interactive Charts with Google Charting APIs" the notebook you're referring to? Which cells are failing and what's the error?
Also, what's the Datalab version you're running? You can find this by going to http://localhost:8081/_info (assuming 8081 is the port Datalab is running on).

**Comment by kazunori279** [comment]
I tried recreating an instance and confirmed it works properly. Closing.
