### ISSUE TITLE
datetime.date(2005, 7, 10) is not JSON serializable

### ISSUE THREAD

**Issue by dovy** [googledatalab/datalab#1199]
Using the `import datalab.bigquery as bq` library in Datalab, and using a pandas dataframe, I try running the insert command:

```
/usr/local/lib/python2.7/dist-packages/datalab/bigquery/_table.pyc in insert_data(self, data, include_index, index_name)
    390           response = self._api.tabledata_insert_all(self._name_parts, rows)
    391         except Exception as e:
--> 392           raise e
    393         if 'insertErrors' in response:
    394           raise Exception('insertAll failed: %s' % response['insertErrors'])

TypeError: datetime.date(2005, 7, 10) is not JSON serializable
```

So does this mean we need to replace date values with strings instead? Seems like data massaging like this should be in the core library. Your input is appreciated.

**Comment by yebrahim** [comment]
This is a legitimate bug with pydatalab. We only convert `datetime.datetime` to ISO strings, but not `datetime.date`. We should fix this, especially since both Legacy and Standard SQL BigQuery now support `Date` types natively.

**Comment by yebrahim** [comment]
For now, can you try switching to using `datetime.datetime` instead? This should be pass as ISO strings.
