### ISSUE TITLE
Git button should point to the repo

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/datalab#1206]
It should always open ungit to the top of where the source repo is located - not to the current folder.

In the current approach, when I am on the root directory in the file view, and open ungit, I am prompted with an ungit UI that says I need to setup a repo. We want users to just use the cloud source repo we clone.

**Comment by yebrahim** [comment]
I'm not sure https://github.com/googledatalab/datalab/issues/1231 actually fixes this. Do we want users to always go to the cloud source repo we clone, or the repo root of whatever dir they're on when they click the ungit icon? I'd say the latter makes more sense.

**Comment by jimmc** [comment]
Discussed with yebrahim. Going to the root of the repo they are in will require a more extensive change that includes a message to the service to figure out where that root is. We agreed that, if we want to make that change, we will open a new issue for that.
