### ISSUE TITLE
datalab create is asking 3 times for "Enter passphrase for key"

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#1214]
Is it possible to enter passphrase key only once during `datalab create`?

**Comment by ojarjur** [comment]
Digging in, we can improve this issue, but not make it go away entirely.

What we can improve is that we were running the SSH command twice (once to make sure the machine was reachable and then once to create the actual tunnel), and in retrospect that wasn't actually necessary.

The bit we can't fix is that gcloud itself will prompt twice for the passphrase the first time a key is created. For instance, if you run `gcloud compute ssh ...` against the same instance, and you do not already have an SSH key pair, then after uploading the public key to your project it will still prompt you for the passphrase twice.

However, at least the day-to-day connection (when you already have a key generated) will only prompt you once.

**Comment by nikhilk** [comment]
Just to be clear, if you don't have a passphrase, you won't be prompted each time, correct?

**Comment by ojarjur** [comment]
@nikhilk No, you won't be prompted in that case.
