### ISSUE TITLE
gcloud command for launching DataLab

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#123]
For beta, we want to have a more streamlined way for DataLab integration with GCP. This is 1 or 2 items (second one is Pantheon)

Gcloud has its own cycle / reviews etc so it would be better to start on this one early. It is also likely simpler than Pantheon integration and follows the API - CLI - UI sequence.

One wrinkle is that we would like to support local usage as well which is not gcloud's purpose. We could treat local launch as either a degenerate case and use gcloud for it as well or continue to provide a non-gcloud script.

**Comment by chmeyers** [comment]
Done
