### ISSUE TITLE
Reseting GCE-VE does not update datalab version

### ISSUE THREAD

**Issue by josecelaya** [googledatalab/datalab#1230]
Running Datalab in GCE option using the CLI commands. Once I open datalab, it tells me that a newer version is available. Following up on the instructions in "Release info", stating that restarting the GCE VM will update datalab, it does not get updated.

I have restarted twice, stopped and started twice. And datalab is not updating.

I have experienced similar issue in the past when using Docker for Datalab and GCE-VM for ipython-kernel. The only way for container version to be updated on the GCE-VM part, was deleting the instance and creating again.

Perhaps this is the correct behavior and just the instructions are incorrect.

@ojarjur

**Comment by ojarjur** [comment]
@josecelaya Sorry; the instructions are wrong. I'll get them fixed.

If you are running locally, then pulling and restarting is fine, but for running in a VM, we have the version pinned (so you don't get accidentally updated), and updating is more complicated.

What you specifically have to do is run:

    datalab delete --keep-disk <VM-name>
    datalab create <VM-name>

To recreate the VM with the newer image. If you explicitly specified a non-default disk name when you first created the VM (i.e. it is something other than "<VM-name>-pd"), then make sure that you specify that again when you recreate the VM so that you get the same persistent disk.

**Comment by ojarjur** [comment]
I've updated the release page in the wiki with the corrected instructions.

**Comment by josecelaya** [comment]
@ojarjur I have noticed a few issues that perhaps should be clarified in the documentation. I found that there are two persistent disk generated. One with the instance name and 20GB space and another one with <instance-name>-pd. I thought that the <>-pd was the important one (since i did not realized there was another one) and recreated a vm with different instance name. This created yet another disk but seems like my code and my documentation are kept on the smaller disk not on the one ending with -pd. 

If you have further explanation about this, please share. I am still a little confused.

**Comment by ojarjur** [comment]
@josecelaya Your initial understanding was right. The "<instance-name>-pd" persistent disk is the one that should contain all of your data (everything under "/content/datalab").

The other disk just holds the host operating system and the Docker images.

What did you see that made you think the other disk was the important one?

**Comment by josecelaya** [comment]
thank you.

I created another VM adding the disk option and it did not have my .ssh key configuration for github. So the procedure mounted the -pd disk but the actual credentials for github were on the other one. Or so it appears to to me.

In any case, I resolved by created a new VM with the exact same name as the original one. Then things worked. So I do not know exactly what get's mounted and where. For instance the "\contents\datalab" space that I see from the notebook, is the on the small disk (os one) or on the large one (-pd one).

The only reason this concerns me is that I will be given some tutorial to 15+ people at work that are new to GCP. I am anticipating issues with this and would like to know as much as possible to troubleshoot on the fly.

cheers
José



José R. Celaya, Ph.D.

Lead Technologist, Data Science
Software Technology Innovation Center
Schlumberger
Menlo Park, CA
CNP<http://www.eureka.slb.com/CNP.cfm?uid=jose-20150518a>

On Mar 14, 2017, at 4:29 PM, Omar Jarjur <notifications@github.com<mailto:notifications@github.com>> wrote:


@josecelaya<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_josecelaya&d=CwMFaQ&c=uGuXJ43KPkPWEl2imVFDmZQlhQUET7pVRA2PDIOxgqw&r=PknZLpsILkbpNJZKwt5YHQ&m=44RxygMs8L3QD3BeKZAtlsI9w0rpN-qfntSI0JaemDk&s=_miJ0_gg1Dlf3mcI1mYaUPiekX7E19i_njgqYI3a4sM&e=> Your initial understanding was right. The "-pd" persistent disk is the one that should contain all of your data (everything under "/content/datalab").

The other disk just holds the host operating system and the Docker images.

What did you see that made you think the other disk was the important one?

**Comment by ojarjur** [comment]
> So the procedure mounted the -pd disk but the actual credentials for github were on the other one.

There should be nothing on the other (small) disk. The Docker container that Datalab runs inside of can't even write to that disk.

> In any case, I resolved by created a new VM with the exact same name as the original one. Then things worked.

The boot disk (the small one) doesn't get reused if you delete and recreate a VM, so if the credentials are working again then they must have been successfully written to the larger persistent disk.

If you try this again can you go look at the disks in the Cloud Console and confirm that the new instance is attached to the same persistent disk that they previous instance was using (i.e. that the command didn't erroneously create a new disk instead of reusing the explicitly specified one)?

**Comment by josecelaya** [comment]
Omar,
I agree with your notes. I think what did not work for me is creating a new instance, with new name, and indicating to use the old disk. In that case, all the files from a few repositories that I had checked before on the original VM, were not listed. But the disk of the original VM was still available. So I created a third VM, now using the same name as the original one, and that seemed to work interns of containing my github credentials.

regards,
José



José R. Celaya, Ph.D.

Lead Technologist, Data Science
Software Technology Innovation Center
Schlumberger
Menlo Park, CA
CNP<http://www.eureka.slb.com/CNP.cfm?uid=jose-20150518a>

On Mar 14, 2017, at 6:08 PM, Omar Jarjur <notifications@github.com<mailto:notifications@github.com>> wrote:


So the procedure mounted the -pd disk but the actual credentials for github were on the other one.

There should be nothing on the other (small) disk. The Docker container that Datalab runs inside of can't even write to that disk.

In any case, I resolved by created a new VM with the exact same name as the original one. Then things worked.

The boot disk (the small one) doesn't get reused if you delete and recreate a VM, so if the credentials are working again then they must have been successfully written to the larger persistent disk.

If you try this again can you go look at the disks in the Cloud Console and confirm that the new instance is attached to the same persistent disk that they previous instance was using (i.e. that the command didn't erroneously create a new disk instead of reusing the explicitly specified one)?
