### ISSUE TITLE
Debug run does not print debug information

### ISSUE THREAD

**Issue by yebrahim** [googledatalab/datalab#1236]
Adding `DATALAB_DEBUG=true` in the `run.sh` script does not print debug information anymore.

**Comment by ojarjur** [comment]
You now have to also add

    -e 'DATALAB_SETTINGS_OVERRIDES={"consoleLogLevel": "debug" }' \

To make it print out the debug logs.

We may want to just explicitly add the two lines to that script, since it should only ever be used for development.

**Comment by yebrahim** [comment]
Thanks for pointing that out, yes I think we should show debug lines by default in the run script.
