### ISSUE TITLE
Windows 10 Home doesn't allow to run the local Docker

### ISSUE THREAD

**Issue by kazunori279** [googledatalab/datalab#1238]
We hosted a [ML codelab](http://www.gdg-sg.org/2017/01/tensorflow-codelab-for-beginner-sat-mar.html) at Singapore yesterday with 150+ attendees. We've used [this instruction](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local) to install the local Datalab.

When we started, we saw about 10 users of Windows 10 Home (they brought their own laptop to the venue) had trouble on the install. Windows 10 Home requires docker toolkit which is not supported by Datalab. We may add a warning on the instruction that it doesn't support Windows 10 Home.

FYI, for other uses with Mac, there were no issue on the installations. I've updated [my codelab instruction](https://github.com/kazunori279/TensorFlow-Intro/blob/master/0.%20Preparation.ipynb) to ask Windows users to use "datalab" command for creating GCE instance.

**Comment by nikhilk** [comment]
The docs are being updated to point all users toward the `datalab` command and instances running on VMs. The local docker option is only for those developing Datalab going forward, and will only be documented in github, not on the cloud docs site.
