### ISSUE TITLE
Fix the version of gcloud to avoid update notifications

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/datalab#1241]
We should probably have a fixed gcloud version to ensure consistent experience and version it with Datalab container versions.

This will also avoid spurious update warnings from gcloud (despite the use of -q) that say this:

````
Updates are available for some Cloud SDK components.  To install them,
please run:
  $ gcloud components update
````

**Comment by ojarjur** [comment]
Fixing the version would block end users from manually upgrading, but we can disable the notification with this command

    gcloud config set component_manager/disable_update_check true
