### ISSUE TITLE
Safari side effect on action top bar (not able to Run anymore)

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#1261]
Chrome view (OK):
![image](https://cloud.githubusercontent.com/assets/8209940/23781207/8662ecd2-0500-11e7-982b-de8ac6b81d38.png)

Safari view (not OK, the Run second bar is no more visible, if you scroll over large output window):
![image](https://cloud.githubusercontent.com/assets/8209940/23781218/994ef778-0500-11e7-8f09-a674714027c8.png)

**Comment by chmeyers** [comment]
Another report of this issue here: http://stackoverflow.com/questions/42773452/menubar-in-datalab-keeps-vanishing

**Comment by yebrahim** [comment]
I'll take a look at fixing this soon. As a workaround for now, if you scroll up till the end, then scroll up again a bit, the bar should come back.
