### ISSUE TITLE
Unable to run quickstart locally

### ISSUE THREAD

**Issue by jason-riddle** [googledatalab/datalab#1262]
I'm trying to create a datalab instance from my personal machine and not from google cloud shell. Running `datalab create my-instance` fails with the following.

```bash
ERROR: (gcloud.compute.networks.create) Some requests did not succeed:
 - Required 'compute.networks.create' permission for '<redacted>'

A nested call to gcloud failed.
```

I'm confused about this error message since I thought I was authenticated as the owner of my account on my local machine. Any tips on how to troubleshoot this?

**Comment by ojarjur** [comment]
@jason-riddle the main tool we provide for debugging such issues is the `--verbosity` flag.

You can re-run your command with `--verbosity=debug` (e.g. `datalab create --verbosity=debug my-instance`) to get more output about what the command is doing when it hits the errors.

You can also confirm that you are authenticated as a project owner by running

```shell
gcloud auth list --filter=status:ACTIVE
```

... to see what your active account is, and then

```shell
gcloud config get-value project
```

... to see what your current project is. Go to the permissions page in the Cloud Console for that project, and confirm that account is listed as an owner.

**Comment by jason-riddle** [comment]
Apologies, I was using the project name instead of the project id. Once I entered in the project id, everything worked fine. Thanks for the help! Closing.

**Comment by arnauddelaunay** [comment]
For those having the same issue, here is how I fixed it : 

 - Be sure you have a project set in your gcloud config. At the beginning, when I ran `gcloud config get-value project` I was receiving `none` meaning that no project was set. 
 - If not set, you need to set your project (to see the list of your projects, just run `gcloud projects list`)
 ``` 
  gcloud config set project <project-id>
 ```
 - Now you can run `datalab list` to check if any datalab project exists (normally none)
 - It will check if your project is linked to a billing account. If not, it will give an url to link your project to a billing account. (`ERROR: (gcloud.compute.instances.list) FAILED_PRECONDITION: Operation does not satisfy the following requirements: billing-enabled`)
 - Once is done, you can peacefully create your datalab project : `datalab create my-instance`

**Comment by rohorner** [comment]
I had a different issue. Executing `datalab list` returned the following error: `API [compute.googleapis.com] not enabled on project. Would you like to enable and retry?  (y/N)?`

I enabled the API and was able to successfully create the datalab instance.
