### ISSUE TITLE
Automatic VM Lifetime Management

### ISSUE THREAD

**Issue by chmeyers** [googledatalab/datalab#1264]
The datalab VMs should save state and stop themselves when nobody is connected and no cells are running.

**Comment by chmeyers** [comment]
Jim, this seems like a decent project to ramp you up further on the codebase. Omar has some ideas around this, so check with him.

This could perhaps use the alpha suspend command: https://cloud.google.com/sdk/gcloud/reference/alpha/compute/instances/suspend

**Comment by jimmc** [comment]
Fixed by #1395.
