### ISSUE TITLE
Docs contain repeated words

### ISSUE THREAD

**Issue by FreddieV4** [googledatalab/datalab#1278]
Found this while browsing through the [Adding Libraries](https://cloud.google.com/datalab/docs/how-to/adding-libraries) how-to docs: `after substituting after substituting`

![image](https://cloud.githubusercontent.com/assets/8339018/24053088/247a69c8-0b0e-11e7-8989-db10d1ae16e0.png)

Figured I'd open up an issue here to let you know 😃

**Comment by chmeyers** [comment]
Thanks.  I've forwarded this to our Technical Writer.

They are not on Github, so for future reference the faster way to report documentation bugs on cloud.google.com/ is to use the "Send Feedback" link on page, as that will file a report directly to the person who can change the page.

**Comment by FreddieV4** [comment]
Awesome. Will do that if I come across anything else. Thanks!
