### ISSUE TITLE
The entire '/content' directory should be mapped to the notebooks disk

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1280]
The current version of the `datalab` command line tool creates instances where the `/content/datalab` directory is mapped to the `datalab` subdirectory of the notebooks disk.

However, there are two issues with this:

1. Why even have the `/content` directory if it isn't writeable in a persistent way?
2. We then loose (with caveats) any data that a user writes to the `/content` directory.

The caveat on the second item is that even though only the `/content/datalab` directory is persisted, the entire `/content` directory is backed up to GCS.

This means we aren't being consistent with our own behavior.

I think the appropriate solution is to map the entire `/content` directory to the notebooks persistent disk.

However, this requires backwards compatibility with existing notebook disks.

To address that, I am thinking of the following logic for newly created instances:

1. After mounting the notebook disk, check if there is a `content` subdirectory on it.
2. If there isn't, then create that directory.
3. If there is a `datalab` directory in the notebook disk, but no `content/datalab` subdirectory, then move the `datalab` directory under the `content` directory.
4. Otherwise, if there is no `datalab` directory under the `content` directory, then create one.
5. When launching the Docker container, always map the `content` directory of the notebooks disk to the `/content` directory in the container.

**Comment by nikhilk** [comment]
I think its good to get a few requirements/scenarios listed to make sure everything makes sense.

1. For completeness, a /tmp that is truly transient
2. A /data directory that is in the PD so it is not temporary, but not backed up to GCS -- for example if I want to download data from the web or GCS/BQ for local work.
3. A /content directory that is backed up to GCS, that contains the git repo clone(s) as well.

**Comment by ojarjur** [comment]
@nikhilk That is good feedback.

I think this moves us more towards that end-state.

1. The `/content` directory will work exactly as you describe.
2. This doesn't conflict with adding a `/data` directory later on (and that does seem like a good feature to add).
3. This doesn't add anything to cleanup the `/tmp` directory, but it also doesn't conflict with that.

We can just reduce the priority of this after the `/content` directory is fixed but leave it open until all three are addressed.

**Comment by ojarjur** [comment]
Actually, on second thought, this issue should be kept for just the bug, and we should create a separate feature request for the changes to the `/data` and `/tmp` directories.
