### ISSUE TITLE
Autocomplete width for Search functionality could be smaller

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1290]
I noticed that the width of the drop down in the new autocomplete search functionality is larger than needed when my browser is maximized. This doesn't affect functionality so feel free to close this issue. I just wanted to share the observation.

![screenshot from 2017-03-28 10-35-51](https://cloud.githubusercontent.com/assets/5184014/24411142/17b29cb8-13a3-11e7-811e-09c07d7b9b76.png)

**Comment by nikhilk** [comment]
+1 ... would be nice to make it fit the longest string. Perhaps the textbox could be a bit larger too?

I think the status indicator ("partial results") could be at the bottom to indicate where more files will go.

**Comment by parthea** [comment]
Closing as obsolete.
