### ISSUE TITLE
`updateMessageArea` hidden under Datalab banner

### ISSUE THREAD

**Issue by craigcitro** [googledatalab/datalab#1295]
This is semi-recent, eg within the last week or two:

![screenshot 2017-03-30 at 1 20 09 pm](https://cloud.githubusercontent.com/assets/468559/24524503/a6594e18-154b-11e7-8e86-19787c23d283.png)

**Comment by chmeyers** [comment]
Yasser, could this be due to https://github.com/googledatalab/datalab/pull/1291?

**Comment by yebrahim** [comment]
Yes it probably is, I'll take a look soon-ish.

**Comment by yebrahim** [comment]
This is working fine for me. It's possible your clone was from before I fixed another css issue with a missing `site` element. If you still have this running, can you make sure you have the following HTML structure:
```
  <div id="app">
    <div id="appBar">
    </div>
    <div id="site">
      <div id="appContent">
    ...
```

**Comment by craigcitro** [comment]
Yep, seems to be fixed. 👍
