### ISSUE TITLE
Using IPywidgets 5.2.2 results in version warning message.

### ISSUE THREAD

**Issue by tylere** [googledatalab/datalab#1298]
The current version (5.2.2) of ipywidgets in Datalab triggers a warning message: "The installed widget Javascript is the wrong version."  This can be reproduced with:

```
import ipywidgets
test = ipywidgets.Text('Hi!')
test
```

Upgrading ipywidgets to the current version (6.0.0) resolves the issue.
`pip install --upgrade ipywidgets
`

**Comment by yebrahim** [comment]
Should be straightforward to fix. Please feel free to send a pull request if you need this fix soon.

**Comment by yebrahim** [comment]
Closing this as a dup of https://github.com/googledatalab/datalab/issues/1245.
