### ISSUE TITLE
Loading extension.js sometimes takes >4 seconds.

### ISSUE THREAD

**Issue by qimingj** [googledatalab/datalab#1301]
It is served from http://127.0.0.1:8081/nbextensions/jupyter-js-widgets/extension.js, and even though status is 304 (not modified), it sometimes takes long time to load. This happens even if datalab has been up and running for a while.

I only tried local run, so don't know whether it also reproduces in GCE.

**Comment by oliviernguyenquoc** [comment]
Same here. About 15s each time I reload my page since the new release (even if it's seems to not to be related to this).

My chrome is saying that 15s is taking to "Content Download" extension.js.

**Comment by yebrahim** [comment]
@oliviernguyenquoc:
- Are you working locally on your machine or using GCE?
- Does this happen only on the first page load or every load?
- Can you paste more details from the networking section of your dev tools?

**Comment by oliviernguyenquoc** [comment]
I have restarted my GCE and it's working now.

I was on a GCE, it was on every load and it was like this but with 15s load each reload:

![image](https://cloud.githubusercontent.com/assets/7463783/24899048/32f029e4-1e9f-11e7-8e8a-f2d3e8877786.png)

But **I have no longer this issue**. I will report it if I see it again.

Thank you for your quick answer.
