### ISSUE TITLE
notebooks accessed using /tree get set as default location

### ISSUE THREAD

**Issue by jimmc** [googledatalab/datalab#1303]
If you browse the tree to a folder containing a notebook, then edit the URL and add the notebook name to create a URL such as locahost:8081/tree/datalab/docs/Readme.ipynb, this location gets saved as the default location, so the next time you access localhost:8081, it opens that notebook.

**Comment by jimmc** [comment]
This behavior is true even if the entered path does not exist. If you add "/foo" to the location line and then get a 404 error, accessing localhost:8081/ will then redirect to that location and give 404 again, until you fix it by entering a path that exists (such as localhost:8081/tree).

**Comment by yebrahim** [comment]
One more way this could happen is if you have a legitimate path saved in the setting, and then delete it from the notebook (something like `!rm -rf path`). Maybe we should think about a custom error page in a different issue?
