### ISSUE TITLE
Problem with apt-get update

### ISSUE THREAD

**Issue by siskaj** [googledatalab/datalab#1314]
I have seen that similar issue was already targeted and closed nevertheless in my today instalation on GCE the problem persist.
apt-get update produces the following:
Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/security.debian.org_dists_jessie_updates_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/ftp.us.debian.org_debian_dists_testing_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/deb.debian.org_debian_dists_jessie-updates_InReleaseW: GPG error: http://security.debian.org jessie/updates InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
W: GPG error: http://ftp.us.debian.org testing InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
W: GPG error: http://deb.debian.org jessie-updates InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
E: Couldn't create temporary file to work with /var/lib/apt/lists/deb.debian.org_debian_dists_jessie_Release - mkstemp (2: No such file or directory)
E: Couldn't create temporary file to work with /var/lib/apt/lists/deb.debian.org_debian_dists_jessie-updates_Release - mkstemp (2: No such file or directory)
E: The package lists or status file could not be parsed or opened.

**Comment by siskaj** [comment]
The problem is obviously difficult to replicate. When I stopped and re-connect Datalab apt-get update worked OK.

**Comment by yebrahim** [comment]
There have been some issues with mounting the `/tmp` directory that were fixed with the latest release. Please let us know if you see this again.

**Comment by chmeyers** [comment]
Yes, anything that mentions temp files is likely to have been https://github.com/googledatalab/datalab/issues/1263
