### ISSUE TITLE
Improve error message when creating a new notebook when the Datalab server is stopped

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1327]
I accidentally stopped the Datalab server after running `datalab connect...` using the Datalab CLI and noticed the following pop up when I tried to create a new Datalab notebook: 

![image](https://cloud.githubusercontent.com/assets/5184014/25288791/f27a71f0-2694-11e7-8989-505a98ea3b19.png)

The error message could be improved. Feel free to close this issue if it is not helpful.

**Comment by jimmc** [comment]
The code that is producing this error message and dialog is down in the Jupyter library. I looked around for a while and did not see an obvious way to fix it, so I'm putting it back on the shelf.

**Comment by nikhilk** [comment]
Is this still going to be the case with the new file listing UI? Are we going through our own equivalent of a content service, or still relying on the notebook server for the content management API?

**Comment by yebrahim** [comment]
We're still relying on the content API provided by Jupyter, but rewriting the frontend entirely, so we'll have to handle these cases ourselves.
This here looks like a 5xx error returned from the Jupyter server, and this is the way the client code chose to handle it.

**Comment by parthea** [comment]
Closing as obsolete.
