### ISSUE TITLE
Have a single command for upgrading an existing datalab instance

### ISSUE THREAD

**Issue by chmeyers** [googledatalab/datalab#1329]
Currently we list these commands to upgrade a datalab instance to the newest version:
datalab delete --keep-disk ${VM-Name}
datalab create ${VM-Name}

Should we combine these into a single "datalab upgrade" command?

**Comment by nikhilk** [comment]
+1

**Comment by yebrahim** [comment]
Closing as dup of https://github.com/googledatalab/datalab/issues/1163. Please +1 that issue.
