### ISSUE TITLE
Update steps for configuring development environment

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1334]
I noticed that the steps in https://github.com/googledatalab/datalab/wiki/Development-Environment haven't been updated in a while. I had some difficulty with the steps. For example, the following commands fail :
```
# Mac
mkdir ~/tools
wget -O ~/tools/miniconda.sh \
    http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
chmod +x ~/tools/miniconda.sh && ~/tools/miniconda.sh
~/tools/miniconda/bin/conda update -all -y
~/tools/miniconda/bin/conda install -y \
    pip ipython=4.2 jinja2 pyzmq tornado requests mock
~/tools/miniconda/bin/pip install httplib2 oauth2client

# add to ~/.bashrc
export PATH=~/tools/miniconda/bin:$PATH

# Linux
Use https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh instead
```

I get 

```
tony@tony-laptop:~$ ~/miniconda2/bin/conda update -all -y
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: -all
```

Also, the default installation location was ~/miniconda2 instead of ~/tools/miniconda/

I also noticed that pip version 9.x was required in my pydatalab development environment.

Would it be ok if I submit a PR to update the instructions  in https://github.com/googledatalab/datalab/wiki/Development-Environment ?

**Comment by yebrahim** [comment]
As far as I know there's no easy way for you to submit a PR for the wiki, please correct me if I'm wrong. If you can do it then please feel free, we can definitely use some updates there.

**Comment by brandondutra** [comment]
I'll update the page to just say get python.
