### ISSUE TITLE
'datalab connect' sometimes failing to create ssh tunnel to existing VM

### ISSUE THREAD

**Issue by chmeyers** [googledatalab/datalab#1340]
(From User Reported Issue)

When this happens 'datalab create' still seems to work and the new VM is fine, the SSH button in Cloud Console still works but 'gcloud compute ssh' doesn't.

Possibly an issue with the SSH keys?  Do they need to be refreshed?

**Comment by ojarjur** [comment]
I dug into this, and believe the issue was caused by the datalab firewall rule (which is automatically added by the `datalab create` command) for that user's project having been replaced by one that did not allow connections from Cloud Shell.
