### ISSUE TITLE
terminal UI improvements

### ISSUE THREAD

**Issue by brandondutra** [googledatalab/datalab#1343]
When I open a new terminal, I would like the following to happen

* use /bin/bash as sh does not do tabs or left arrow
* have $HOME set to /content, to match the file browser
* land in $HOME instead of /
* print a big message telling users what /content is and any file changes outside of /content will be lost when the container stops. Explicitly say things like installing packages and updating config files will be lost if they live outside of /content

**Comment by yebrahim** [comment]
Fixed in https://github.com/googledatalab/datalab/pull/1355.
