### ISSUE TITLE
As of the 154.0.0 release of the Cloud SDK, `datalab connect` no longer works on Windows

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1356]
It seems that with release 154.0.0, the `gcloud compute ssh` command took out the platform-specific sanitation that it performed on SSH flags.

Previously, passing in `--ssh-flag=-o --ssh-flag=LogLevel=info` was a no-op on Windows, as the gcloud command new to ignore the `-o` option since PuTTY does not support it.

As of the 154.0.0 release, however, this is no longer the case, and the -o flag is passed to PuTTY, which then fails saying it does not recognize that option.

The known work-arounds for this issue are:

1. Downgrade to version 153.0.0 of the Cloud SDK, or
2. Use the Cloud Shell to run `datalab connect`

**Comment by ojarjur** [comment]
Version 155.0.0 of the Cloud SDK was released this morning, and that latest version includes the fix for this issue.

**Comment by TheOddler** [comment]
I'm getting a similar bug on Windows, but now Putty is complaining about the unknown options '-it'

![image](https://user-images.githubusercontent.com/1831376/34917097-0a5aa21a-f942-11e7-8734-d29324126907.png)

Is this problem back? Or is this a different problem?

I'm running:

```
Google Cloud SDK 184.0.0
beta 2017.09.15
bq 2.0.28
core 2018.01.05
gsutil 4.28
```
And putty 0.70

**Comment by ojarjur** [comment]
@TheOddler No, I believe what you are seeing is a different issue.

It looks like what you are hitting is an issue with the `gcloud compute ssh` command's `--container` flag not working on windows. If you use `datalab connect` to connect to the instance, or `gcloud compute ssh` without the `--container` flag, then the issue should not reproduce.

If that is correct (i.e. you try those other two commands and they work), then please file a bug against the Cloud SDK using [this link](https://issuetracker.google.com/issues/new?component=187143&template=0).
