### ISSUE TITLE
biguery parameter not passed to %%chart

### ISSUE THREAD

**Issue by rawnaq** [googledatalab/datalab#1364]
when parametrizing in this way:

```
%%bq query -n endpoint_stats
SELECT *
FROM `cloud-datalab-samples.httplogs.logs_20140615`
WHERE endpoint = @endpoint
LIMIT 10

%%bq execute -q endpoint_stats
parameters:
- name: endpoint
  type: STRING
  value: Interact2
```

the parameter doesn't get passed to %%Chart. is that a bug or missing feature?

**Comment by yebrahim** [comment]
This is indeed missing, thanks for reporting @rawnaq.
We should also move this issue to the pydatalab repo.

**Comment by yebrahim** [comment]
Opened https://github.com/googledatalab/pydatalab/issues/374 instead, closing this one.
