### ISSUE TITLE
datalab list not working

### ISSUE THREAD

**Issue by brandondutra** [googledatalab/datalab#1366]
$datalab list
Listed 0 items.

But I have make two instances with datalab create: https://screenshot.googleplex.com/Agykjd3aO5o.png

gcloud info
Google Cloud SDK [155.0.0]
Installed Components:
  core: [2017.05.10]
  datalab: [20170505]
  gcloud: []
  docker-credential-gcr: []
  beta: [2017.03.24]
  gsutil: [4.26]
  bq: [2.0.24]
  alpha: [2017.03.24]

I think datalab is trying to call 'gcloud instances list', but it should be 'gcloud compute instances list'. Also, I thought in the past pantheon would put a label on my DL instances, but I don't see it now.

**Comment by ojarjur** [comment]
The label is the issue.

It seems that the previously documented behavior of having tags show up as empty labels (which could be filtered on in list calls) has been removed.

It was a beta feature (i.e. had no stability guarantee), so it was a mistake to rely on that anyway.

We should change the logic to list all instances, and then filter that list on the client side to only instances with a `datalab` tag.
