### ISSUE TITLE
Error message improvement: Error loading notebook  Type u'notebook&_=1495545190018' is invalid

### ISSUE THREAD

**Issue by waltermblair** [googledatalab/datalab#1377]
Similar to this SO question (https://stackoverflow.com/questions/44124649/error-opening-datalab-notebooks-all-files), I'm unable to open any of my Datalab notebooks, though I can open non-ipynb files.
Perhaps the issue I'm actually submitting for the product is that the error message should be improved.

**Comment by yebrahim** [comment]
@waltermblair can you paste the output of `http://localhost:8081/_info` here?

**Comment by chmeyers** [comment]
We've had a couple of reports of this, but I wasn't able to repro it locally or on the cloud just now.  Since we use hermetic docker images, I'm guessing this points to some external dependency being down?

**Comment by qimingj** [comment]
@waltermblair if you try to create a new notebook, what happens?

**Comment by chmeyers** [comment]
Okay, this looks to happen when connecting to Datalab using Cloud Shell, so it's likely that a change in Cloud Shell is causing this.  We're following up with them internally.  Short term workaround is to connect to Datalab without using Cloud Shell.

**Comment by chmeyers** [comment]
After followup with Cloud Shell, this should now be fixed.

**Comment by jmhehir** [comment]
I had the same issue and it is working for me now.  Thanks!

**Comment by waltermblair** [comment]
This works for me now too, you fixed it thanks!

**Comment by hjain4** [comment]
I am facing same issue again..
[log.txt](https://github.com/googledatalab/datalab/files/1167247/log.txt)
