### ISSUE TITLE
Experimental UX ApiManager ignores basePath

### ISSUE THREAD

**Issue by chmeyers** [googledatalab/datalab#1453]
'/api/sessions' and '/api/contents' are hardcoded currently and not relative to the Datalab Base Path

**Comment by chmeyers** [comment]
These are in datalab/sources/web/datalab/polymer/modules/ApiManager.ts.

I'd go and fix them, but it would probably take me 10x as long to figure out how to.

**Comment by yebrahim** [comment]
I think you already fixed this. Re-open if not.
