### ISSUE TITLE
Include a message on connection telling how to reconnect if the connection is cancelled.

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1519]
When this info is output on instance creation:

    The connection to Datalab is now open and will remain until this command is killed.
    You can connect to Datalab at http://localhost:8081/

... also include a message saying how to reconnect (i.e. to run `datalab connect ...`)

**Comment by umang-sh** [comment]
I would like to contribute to this - I am a newbie to datalab

**Comment by chmeyers** [comment]
umang-sh, feel free.  This would be under https://github.com/googledatalab/datalab/blob/master/tools/cli/commands/connect.py

**Comment by umang-sh** [comment]
@chmeyers  ,Was traveling .
Now I am on it , will do a pull request soon after fixing this.
You can make me assignee with this issue :)

**Comment by yebrahim** [comment]
Github only allows repo members to be assignees on issues as far as I know. :) Still, feel free to work on this and send a PR.

**Comment by umang-sh** [comment]
@chmeyers  @yebrahim  I am trying to do a git push -u origin <my branch name> it throws an error saying : 
remote: Permission to googledatalab/datalab.git denied to umang-sh.

what shall I do ? I am trying to do a pull request by following the method mentioned here: 
https://github.com/googledatalab/datalab/wiki/Developer-Workflow

please help :)

**Comment by nikhilk** [comment]
Can you create a pull request from your fork? Someone on the datalab team will need to review/merge.

**Comment by yebrahim** [comment]
Expanding on @nikhilk's comment, you'll need to work on a fork of this repo, which you can create that on Github. After you have your fork, clone that to your dev environment and do your work there, and push it to any new branch on your fork. You can then switch to the main Datalab repo (this one) and start a pull request, which the team can review and merge.

**Comment by umang-sh** [comment]
@nikhilk  @yebrahim @chmeyers  I have created a pull request :) 
Let me know for any changes

**Comment by umang-sh** [comment]
@ojarjur  @nikhilk 
You may close this issue , this has been solved and merged via the approved pull request here :) 
https://github.com/googledatalab/datalab/pull/1759

Thank you @yebrahim @nikhilk @chmeyers @ojarjur for all your help and guidance ,in making this contribution successful :)   


I am looking to do more contributions,please suggest anything I can work and contribute on :)

**Comment by ojarjur** [comment]
Thanks @umang-sh. I'm going to throw in one more feature before closing this bug out, but I appreciate your help with this.

More specifically, I realized that we could generate the exact command to re-run (rather than an example command), so I'm going to build on your change to also do that.
