### ISSUE TITLE
Any way to prevent Datalab from connecting/creating its own separate [datalab] network, and force it to connect to the default vpc?

### ISSUE THREAD

**Issue by donjae** [googledatalab/datalab#1535]
I've been looking at the docs, and there seems to be no way to create a datalab instance within the default VPC. It's really causing issues with interoperability

**Comment by fabito** [comment]
I'm facing the same issue. I need to access services on a GKE cluster running on the default network through an internal load balancer.

I tried to create the `datalab-network` myself but then the `datalab create` command raised:

```
DEBUG: (gcloud.compute.instances.create) Could not fetch resource:
 - Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network
Traceback (most recent call last):
  File "/home/user/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 787, in Execute
    resources = args.calliope_command.Run(cli=self, args=args)
  File "/home/user/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 754, in Run
    resources = command_instance.Run(args)
  File "/home/user/google-cloud-sdk/lib/surface/compute/instances/create.py", line 455, in Run
    return compute_client.MakeRequests(requests)
  File "/home/user/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 89, in MakeRequests
    errors, error_message='Could not fetch resource:')
  File "/home/user/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 106, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/home/user/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 118, in RaiseException
    errors))
ToolException: Could not fetch resource:
 - Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network

ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Invalid value for field 'resource.networkInterfaces[0]': ''. Subnetwork should be specified for custom subnetmode network
```
I thinkg a `--network` argument would make things easier.

**Comment by jonbuffington** [comment]
@fabito As a temporary workaround, I modified https://github.com/googledatalab/datalab/blob/master/tools/cli/commands/create.py#L36 locally to use the name of the existing VPC where I wanted the datalab instances to be allocated. E.g., instead of `_DATALAB_NETWORK = 'datalab-network'`, it would be `_DATALAB_NETWORK = 'default'`.

**Comment by donjae** [comment]
@fabito Yeah, I totally think a --network flag to define the network would be the best solution imo

**Comment by chmeyers** [comment]
As an FYI, the main reason why we haven't done this yet is because exposing this makes it easy for users to shoot themselves in the foot and accidentally expose their Datalab VM to the entire internet.

We discussed this internally and we likely will still add it, but it will have to have some additional warning messages to go along with it.

**Comment by donjae** [comment]
@chmeyers How about if the user utilizes the --network flag for their datalab, and there's a warning prompt that notifies the user that the network connected has a allow external connections tag? Or perhaps at least disable inbound external connections that's default for the vm?

I feel like there's alot of solutions to address it. But totally understand the hesitation to allow a feature like this.
