### ISSUE TITLE
New Notebook dialog shows file list without scrollbar

### ISSUE THREAD

**Issue by jimmc** [googledatalab/datalab#1551]
In the Polymer UI, when the New Notebook dialog is showing a list of files that is taller than the dialog, the list does not include a scrollbar, but instead pushes the input field below it down. The buttons remain in the right place. As a result, the button overlap the input field, as shown below. If the file list is longer, the input field disappears off the bottom of the dialog.

![new-notebook-dialog-bug](https://user-images.githubusercontent.com/116825/28984864-cbe55ed8-7914-11e7-8dfd-902f583c8d38.png)

**Comment by jimmc** [comment]
Still not quite right, the input field and the buttons can still overlap when the dialog opens and is too small. It fixes itself when I resize to make it larger then back down.
![file-save-overlap](https://user-images.githubusercontent.com/116825/29041032-2c0d6e24-7b66-11e7-991d-a4fd5a5f413b.png)

**Comment by yebrahim** [comment]
I'm reworking all the resizable elements to use flexboxes, will send a PR soon.
