### ISSUE TITLE
Sign in button doesn't appear to work in Polymer UI

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1579]
Hello,

I'm running Datalab in local (development mode) with the following environment variable to enable the Polymer (experimental) UI: `-e DATALAB_EXPERIMENTAL_UI=true`

When I click the sign-in button nothing happens.
![image](https://user-images.githubusercontent.com/5184014/29382465-9d7c3172-829a-11e7-812a-f72f18b22da6.png)

I noticed the following related error in my browser console:
```
Uncaught (in promise) Error: Error in gapi auth: Not a valid origin for the client: http://127.0.0.1:8081 has not been whitelisted for client ID x.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID.
    at gapi.auth2.init.then (gapi-manager.js:123)
    at h.o0 (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_GB.x.O/m=auth…/d=1/ed=1/am=AQ/rs=x/cb=gapi.loaded_0:107)
    at xs (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_GB.x.O/m=auth…/d=1/ed=1/am=AQ/rs=x/cb=gapi.loaded_0:110)
    at Wq (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_GB.x.O/m=auth…/d=1/ed=1/am=AQ/rs=x/cb=gapi.loaded_0:110)
    at _.C.uea (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_GB.x.O/m=auth…/d=1/ed=1/am=AQ/rs=x/cb=gapi.loaded_0:109)
    at Ap (apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en_GB.x.O/m=auth…/d=1/ed=1/am=AQ/rs=x/cb=gapi.loaded_0:103)
    at <anonymous>
```
I think this error is preventing me from using other parts of the Polymer UI. I don't see the button to create a new notebook.

I'll revert back to the old UI. I just wanted to try the Polymer UI to see if I could contribute to it. 

Feel free to close this issue since this UI is not released yet.

**Comment by yebrahim** [comment]
I'm not sure why this is happening, but until we investigate further, try adding your own oauth client id under settings.
To do this, edit the file `/datalab/.config/settings.json` and add a `oauth2ClientId` field in the JSON with your client ID, which you can get from your cloud console.

Keep in mind we still don't have a finished piece that's using the sign in auth in the new UI.

**Comment by jimmc** [comment]
The client ID we are currently using by default requires that you use "localhost" instead of "127.0.0.1" in your browser URL. I'll get that changed to include 127.0.0.1.
The Files, Sessions, and Terminal tabs in the new UI are all currently independent of the account sign-in, so should work even if the sign-in fails.

**Comment by jimmc** [comment]
The default client ID has been updated to allow 127.0.0.1, but it looks like there are other parts of the system that still cause that not to work. For now, I think we can only support localhost. If  you want to experiment with other source URLs, you can use your own client ID as described by yebrahim above.
