### ISSUE TITLE
Datalab failed to open localhost - idleTimeout

### ISSUE THREAD

**Issue by HaipengSu** [googledatalab/datalab#1592]
I pulled the latest version of Datalab image ( Datalab 1.2.20170818) and use the same command to run datalab, however, it keeps throwing the following errors and I can't open datalab in my localhost.

`docker run -it -e DATALAB_DEBUG=true --name=datalab -p "127.0.0.1:8081:8080" -v "${HOME}/git/datalab:/content" -e "PROJECT_ID=my-project" gcr.io/cloud-datalab/datalab:local`

![image](https://user-images.githubusercontent.com/13719899/29460135-cae440b8-83f4-11e7-8777-38ab4fa16f83.png)

Still trying to get it working. Any suggestions? 
thank you

**Comment by jimmc** [comment]
I was able to reproduce this error by creating a settings file with invalid json. Take a look at $HOME/datalab/.config/settings.json and see if it looks like valid JSON; if not, edit it to make it valid and see if that fixes the problem. I have seen the problem where a comma between properties in settings.json had been replaced by a close-brace.
The other thing you can do is to turn up the logging level by adding this to the docker command:
   -e "DATALAB_SETTINGS_OVERRIDES={\"consoleLogLevel\": \"debug\" }"
See if that produces a SyntaxError log line just before the traceback.

**Comment by HaipengSu** [comment]
@jimmc It works. didn't know how the path in setting.json file was changed to some invalid path. 

But it is working now. Thank you so much.
