### ISSUE TITLE
Show line numbers by default when re-opening notebook

### ISSUE THREAD

**Issue by IamJeffG** [googledatalab/datalab#1604]
When creating a new cell in a Python notebook (e.g. by clicking the "Add Code" button or typing `a` or `b` in command mode) the new cell has line numbers showing by default.  (I find this helpful, because I click on the line number margin to toggle between command mode and edit mode; without the line number margin, mode change is not possible with mouse, only via the Escape key.)

However, if I save the notebook, close it, and re-open it, all line numbers disappear.  If I want them back I'd have to use the [undocumented](https://github.com/googledatalab/datalab/issues/1532) keyboard shortcut to toggle line numbers on every single cell, which is impractical; I know of no way to toggle them for all cells.

So, I'd like to simply request line numbers are enabled on all code cells upon opening a notebook. (If for some reason this is untenable as default behavior, then my secondary ask would be to have a button or shortcut to turn line numbers on for all code cells.)

**Comment by yebrahim** [comment]
This is a bug, thanks for reporting it. #1605 should fix it.

**Comment by IamJeffG** [comment]
I went back to jupyter notebook to better understand the good behavior I'm used to. Turns out they also keep line numbers off by default, and I've never had a problem with it. I now think the problem with datalab cells are twofold:

1. Datalab does not make it easy to switch between Command and Edit mode via mouse (the `Esc` key is the tiniest sliver of a key on my keyboard so I look for alternatives where possible).  Jupyter makes it easy: they provide a wide left margin you can click on to enter Command mode, or else click on the cell itself to enter Edit mode.  This margin is separate from their line numbers, which are default off but I turned on for this screenshot to highlight the distinction.

![screenshot from 2017-08-25 06-53-00](https://user-images.githubusercontent.com/2002703/29716986-58ceb59e-8962-11e7-96ff-5276824e6835.png)


2. Datalab has inconsistent default behavior around line numbering.  Open a new notebook and your first code cell has no line number.  Now insert a second cell and it has one:

![peek 2017-08-25 06-51](https://user-images.githubusercontent.com/2002703/29717051-9c808510-8962-11e7-9995-555c7662562f.gif)

Problem 2 is quirky, but not something I notice or am bothered by in the normal course of data science.

When I opened this issue my intent related to problem 1, i.e. to provide an alternative to `Esc` to enter command mode on a specific cell.  My initial request for line numbers is really more about extending the clickable screen area from what's otherwise a 4px left-border, and much less about actually seeing line numbers for reference.  I assume there it was a reason you removed the left cell margin and its functionality: maybe if I better understood the intent of that, we could work out a good solution?
