### ISSUE TITLE
Running google cloud datalab on GKE

### ISSUE THREAD

**Issue by fabito** [googledatalab/datalab#1633]
I deployed datalab to my GKE cluster:

```bash
kubectl run datalab --image gcr.io/cloud-datalab/datalab:latest --port 8081
```
Then I tried forwarding (`kubectl port-forward`) a local port to port 8081 on the datalab POD, but requests are not reaching the POD.

What am I my missing ? Is it due to IP address binding issue ?

**Comment by chmeyers** [comment]
The most likely issue is that you need to use port 8080 and not 8081.

The datalab web server serves on port 8080 unless you override it.  8081 is the port we use for mapping locally through an ssh tunnel.

**Comment by fabito** [comment]
Thanks that worked!
