### ISSUE TITLE
Upgrade Tensorflow versions in both cpu and gpu Dockerfiles

### ISSUE THREAD

**Issue by MMMarcy** [googledatalab/datalab#1654]
Hi!

The current Tensorflow versions included are outdated. Is that intended?
Specifically, in the CPU Dockerfile the version is 1.2.0, while in the GPU one is 1.0.1  and the latest stable release of Tensorflow is 1.3.0.

**Comment by qimingj** [comment]
TF (non GPU) 1.2 is intended. TF (GPU) 1.01 will soon be upgraded to 1.2 as well.

**Comment by qimingj** [comment]
Addressed in #1657.
