### ISSUE TITLE
ipywidgets fail to render in Datalab

### ISSUE THREAD

**Issue by tylere** [googledatalab/datalab#1689]
# Setup information

Datalab Version: 1.2.20170818 installs:

- ipywidgets 4.2.3
- notebook 6.0.0

<details>
<summary>Installation details:</summary>

    datalab create test1-instance

    Creating the instance test1-instance
    Created [https://www.googleapis.com/compute/v1/projects/earth-engine-team-datalab/zones/us-central1-a/instances/test1-instance].
    Connecting to test1-instance.
    This will create an SSH tunnel and may prompt you to create an rsa key pair.
    Waiting for Datalab to be reachable at http://localhost:8081/

    The connection to Datalab is now open and will remain until this command is killed.
    You can connect to Datalab at http://localhost:8081/
</details>

# Results

Instead of rendering correctly, the following message is displayed:

> Widget Javascript not detected.  It may not be installed or enabled properly.

The behavior seems consistent whether Datalab is run locally or on GCP.

![image](https://user-images.githubusercontent.com/92862/30718318-707042e4-9ed4-11e7-920c-ef71d9fd293d.png)

**Comment by tylere** [comment]
Similar behavior occurs when running the "Preview" version of Datalab, although the browser's console reports different errors.

# Setup information

<details>
<summary>Dockerfile</summary>

    FROM gcr.io/cloud-datalab/datalab:latest
    env DATALAB_EXPERIMENTAL_UI true
</details>

<details>
<summary>Installation details:</summary>

    docker build --tag=datalab-test .
    Sending build context to Docker daemon     31MB
    Step 1/2 : FROM gcr.io/cloud-datalab/datalab:latest
     ---> 43e710d36020
    Step 2/2 : ENV DATALAB_EXPERIMENTAL_UI true
     ---> Using cache
     ---> 042d709e8742
    Successfully built 042d709e8742
    Successfully tagged datalab-test:latest

    docker run -it --rm -p "127.0.0.1:8081:8080" -v "$WORKSPACE:/content" datalab-test
    Verifying that the /tmp directory is writable
    The /tmp directory is writable
    / /
    From https://github.com/googledatalab/notebooks
     * branch            master     -> FETCH_HEAD
    HEAD is now at d4a8466 Add a TensorFlow sample notebook showing how to build an RNN 
    model with Estimator API. (#128)
    /
    Already on 'master'
    Your branch is up-to-date with 'origin/master'.
    Starting Datalab in silent mode, for debug output, rerun with an additional '-e 
    DATALAB_DEBUG=true' argument
    Open your browser to http://localhost:8081/ to connect to Datalab.
</details>

# Results

![image](https://user-images.githubusercontent.com/92862/30720494-94abe35e-9edc-11e7-8d7d-d3cfb718f4e7.png)

**Comment by yebrahim** [comment]
@tylere I'm having difficulty reproducing this issue. Can you tell me more about this notebook? Does it contain ant embedded SVG images? Or are you seeing this with all notebooks, even simple ones?

**Comment by tylere** [comment]
I tried it out again, and now it seems to work.

I note that the Image ID of the datalab:latest container (43e710d36020) is still the same, but the Image ID after setting the environment variable is different (042d709e8742 vs. 2879828eb5f7).

Below is my setup information for this test.

<details>
<summary>Dockerfile</summary>

```
FROM gcr.io/cloud-datalab/datalab:latest
env DATALAB_EXPERIMENTAL_UI true
```
</details>

<details>
<summary>Installation details:</summary>

```
docker build --tag=datalab-test-2017-12-19 .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM gcr.io/cloud-datalab/datalab:latest
 ---> 43e710d36020
Step 2/2 : ENV DATALAB_EXPERIMENTAL_UI true
 ---> Running in 3203b9e3f048
 ---> 2879828eb5f7
Removing intermediate container 3203b9e3f048
Successfully built 2879828eb5f7
Successfully tagged datalab-test-2017-12-19:latest

docker run -it --rm -p "127.0.0.1:8081:8080" datalab-test-2017-12-19:latest
Verifying that the /tmp directory is writable
The /tmp directory is writable
Cloning into 'docs'...
remote: Counting objects: 588, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 588 (delta 65), reused 47 (delta 47), pack-reused 508
Receiving objects: 100% (588/588), 22.06 MiB | 4.21 MiB/s, done.
Resolving deltas: 100% (296/296), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Starting Datalab in silent mode, for debug output, rerun with an additional '-e DATALAB_DEBUG=true' argument
Open your browser to http://localhost:8081/ to connect to Datalab.
```
</details>

1. Open up a browser: http://localhost:8081/files
2. Create a notebook test.ipynb, import libraries, and test out displaying a widget.

```
import notebook
import ipywidgets
print(notebook.__version__)
print(ipywidgets.__version__)
ipywidgets.IntSlider()
```

![image](https://user-images.githubusercontent.com/92862/34182429-1498673e-e4cb-11e7-9f0f-87b1b02d6838.png)

**Comment by yebrahim** [comment]
On latest master, and after a [race condition](https://github.com/googledatalab/datalab/commit/35e1bc88451fcef704ef81e827c5c357cc7f44a8) has been fixed, I cannot find a good repro for this bug, so I'll just close it. Please make sure to open it again if you see it happen.
