### ISSUE TITLE
Upgrade TensorFlow to the latest version?

### ISSUE THREAD

**Issue by cindy-essence** [googledatalab/datalab#1803]
The version of TensorFlow I'm seeing in Datalab is version 1.2, while the latest version available is 1.4. Could you please update to the latest version of TensorFlow? Some basic tutorials on TensorFlow website don't work under the old version, such as the part for "tf.estimator" here: https://www.tensorflow.org/get_started/get_started.

Thanks!

**Comment by baharw** [comment]
I am having the same problem. Does anyone know how to upgrade the Tensorflow in an existing Datalab. 

Thank you in advance!

**Comment by kazunori279** [comment]
`!pip install -U tensorflow` does the upgrade (for CPU only).

**Comment by karrey05** [comment]
!pip install -U tensorflow  works for me.  But after restarting the compute engine, the datalab will go back to tensorflow 1.2 version.  Do you need to upgrade tensorflow everytime when you restart the engine? Thanks.

**Comment by rileyjbauer** [comment]
As of 37a2206, Datalab is using Tensorflow 1.5
Closing this issue.
