### ISSUE TITLE
Support pulling private custom images

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1822]
Right now, we pull the specified Docker image without providing any credentials to the `docker pull` command.

Ideally, we should configure Docker to use the VM's service account credentials when pulling images from GCR. That would allow us to support private custom images.

I *believe* that this just requires adding a line like ` ExecStartPre=docker-credential-gcr configure-docker` to [here](https://github.com/googledatalab/datalab/blob/master/tools/cli/commands/create.py#L197).

However, this would need to be tested.

**Comment by pcejrowski** [comment]
That would be perfect to have that feature. Actually, the solution you proposed worked for us before.
