### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by karthinuk107** [googledatalab/datalab#1835]
I got a typescript error while running ./build.sh

test/item-list-test.ts(152,5): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(153,5): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(549,9): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(550,9): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(561,9): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(562,9): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(573,9): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(574,9): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(622,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(623,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(627,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(628,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(636,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(637,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(641,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(642,7): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(661,9): error TS2554: Expected 2 arguments, but got 1.
test/item-list-test.ts(683,9): error TS2554: Expected 2 arguments, but got 1.
test/notebook-preview-test.ts(82,14): error TS2345: Argument of type '{}' is not assignable to parameter of type 'boolean'.
test/notebook-preview-test.ts(97,14): error TS2345: Argument of type '{}' is not assignable to parameter of type 'boolean'.
test/notebook-preview-test.ts(112,14): error TS2345: Argument of type '{}' is not assignable to parameter of type 'boolean'.
test/notebook-preview-test.ts(125,14): error TS2345: Argument of type '{}' is not assignable to parameter of type 'boolean'.
test/notebook-preview-test.ts(138,14): error TS2345: Argument of type '{}' is not assignable to parameter of type 'boolean'.
test/notebook-preview-test.ts(151,14): error TS2345: Argument of type '{}' is not assignable to parameter of type 'boolean'.
test/notebook-preview-test.ts(162,14): error TS2345: Argument of type '{}' is not assignable to parameter of type 'boolean'.

**Comment by chmeyers** [comment]
Yasser, you were the last one to touch those files in https://github.com/googledatalab/datalab/pull/1812 and  https://github.com/googledatalab/datalab/pull/1830, can you take a look.

karthinuk107, it might be useful to know which version of Typescript you have installed.
