### ISSUE TITLE
Swap file initialization during start takes too long

### ISSUE THREAD

**Issue by chmeyers** [googledatalab/datalab#1839]
Especially evident on large memory instances, as the swap file size is based on the amount of memory.

Any way we can skip initializing the swap file with zeroes like that?

**Comment by ojarjur** [comment]
I'm thinking this might be resolvable by making two changes:

1. Add a flag to the `create` command that disables the swapfile management on the instance. Users of high memory instances may not want swap enabled, and this would give them the option to turn it off.
2. Automatically disable the swapfile management if the size of memory on the instance is large relative to the disk size. For instance, if the swapfile would take more tha 10% of the disk, then we probably should not be configuring swap.

**Comment by alexgorbachev** [comment]
Thanks @ojarjur

**Comment by ojarjur** [comment]
Note that the fix will not be included in the Cloud SDK until the next Cloud SDK release (i.e. until version 184.0.0)
