### ISSUE TITLE
Dataflow GPU instance can't run GPU with TF 1.4

### ISSUE THREAD

**Issue by kazunori279** [googledatalab/datalab#1879]
Steps to reproduce:

- Create Datalab GPU instance
- `!pip install -U tensorflow-GPU`
- Restart the session
- `import tensorflow as tf`
- You will get `ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory`

This doesn't happen if you're using the default TF 1.2.

**Comment by chmeyers** [comment]
TF 1.4 requires cuDNN v6.0 and the Datalab GPU image currently has cuDNN v5 installed (https://github.com/googledatalab/datalab/blob/master/containers/base/build.gpu.sh#L35)
