### ISSUE TITLE
Enabling "os-login" on a project breaks the ability to connect to Datalab instances in that project.

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1929]
Repro steps:

1. In the project common-instance metadata, add "enable-oslogin=TRUE".
2. Attempt to connect to a Datalab instance.

This will cause the connection to fail with a "Permission denied" error.

You can fix this by adding a "enable-oslogin=FALSE" metadata entry to the Datalab instance, after which the connection will work again (it appears that you do not need to restart the instance).

We may need to preemptively add a "enable-oslogin=FALSE" metadata entry to every Datalab instance we create, until/unless we can make the `datalab connect` command work with os-login

**Comment by fcjbispo** [comment]
Hi, 
Setting up metada os-login had no effect for me, but this one did:
gcloud compute ssh <instance-name> -- -N -p 22 -L 8081:localhost:8080
