### ISSUE TITLE
Unable to connect to datalab - permission denied

### ISSUE THREAD

**Issue by datamiles** [googledatalab/datalab#1932]
Hello Datalab team,

I have launched a datalab instance and I am unable to connect to it via CloudShell. From the console I can SSH to the instance. However from CloudShell I am not having much luck. Here is the command that I run:

s_nasir@cpb100200300:~$ datalab connect dataengvm
Connecting to dataengvm.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':

In the process of connecting - it asks me to enter pass phrase three times (not sure why that is) - then it fails to connect, and brings me back to the passphrase prompt. If I just hit enter it doesnt ask me three times and throws permission denied after first attempt. 

I have checked the firewall rule - and that looks ok. I do have datalab network rule for tcp 22.

Here is the out with the flags: --verbosity=debug --ssh-log-level=debug . I have modified the SSH key with a dummy one for security reasons.

s_nasir@cpb100200300:~$ datalab connect dataengvm --verbosity=debug --ssh-log-level=debug
Connecting to dataengvm.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Connecting to dataengvm via SSH
Waiting for Datalab to be reachable at http://localhost:8081/
DEBUG: Running [gcloud.compute.ssh] with arguments: [--ssh-flag: "['-o', 'LogLevel=debug', '-4', '-N', '-L', 'localhost:8081:localhost:8080']", --verbosity: "debug", --zone: "us-central1-a", [USER@]INSTANCE: "datalab@dataengvm"]
DEBUG: Current SSH keys in project: [u's_nasir:ssh-rsa 
**REMOVED THIS SECTION**
DEBUG: Running command [/usr/bin/ssh -t -i /home/s_nasir/.ssh/google_compute_engine -o CheckHostIP=no -o HostKeyAlias=compute.8049792506287366428 -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/home/s_nasir/.ssh/google_compute_known_hosts -o LogLevel=debug -4 -N -L localhost:8081:localhost:8080 datalab@35.224.80.206].
DEBUG: Executing command: ['/usr/bin/ssh', '-t', '-i', '/home/s_nasir/.ssh/google_compute_engine', '-o', 'CheckHostIP=no', '-o', 'HostKeyAlias=compute.8049792506287366428', '-o', 'IdentitiesOnly=yes', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/home/s_nasir/.ssh/google_compute_known_hosts', u'-o', u'LogLevel=debug', u'-4', u'-N', u'-L', u'localhost:8081:localhost:8080', u'datalab@35.224.80.206']
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 35.224.80.206 [35.224.80.206] port 22.
debug1: Connection established.
debug1: identity file /home/s_nasir/.ssh/google_compute_engine type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/s_nasir/.ssh/google_compute_engine-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u2
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.5
debug1: match: OpenSSH_7.5 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 35.224.80.206:22 as 'datalab'
debug1: using hostkeyalias: compute.8049792506287366428
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:Y7mN67Xx5W9yziSDoaOWZ69d3YoSBllzLL2bXrd/lxg
debug1: using hostkeyalias: compute.8049792506287366428
debug1: Host 'compute.8049792506287366428' is known and matches the RSA host key.
debug1: Found key in /home/s_nasir/.ssh/google_compute_known_hosts:14
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/s_nasir/.ssh/google_compute_engine
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':

Would like to get some advice. I have stopped and restarted the instance - as well as created the instance multiple times but not luck.

Thanks

**Comment by datamiles** [comment]
Also when I SSH to the VM via the console and run docker ps command I do see the datalab container:

CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS              PORTS                      NAMES
38fc3420495a        gcr.io/google_containers/fluentd-gcp:1.18   "/bin/sh -c '/usr/..."   52 minutes ago      Up 52 minutes                                  logger
4843bd9a1e31        gcr.io/cloud-datalab/datalab:latest         "/datalab/run.sh"        52 minutes ago      Up 52 minutes       127.0.0.1:8080->8080/tcp   datalab

thought I add this tid bit of detail here. 

thanks

**Comment by eilalan** [comment]
Based on my experience #1928 the log file on the machine at /var/log/startupscript.log could tell me what is the issue. $cat /var/log/startupscript.log and $cat /var/log/startupscript.log | grep -i err to have the error line location.

**Comment by datamiles** [comment]
Thanks for getting bck Eilalan. 

I SSH'ed into the datalab and ran the command cat /var/log/startupscript.log:

mydatalabvm s_nasir # cat /var/log/startupscript.log
-- Logs begin at Wed 2018-01-31 15:18:49 UTC, end at Wed 2018-01-31 15:19:12 UTC. --
Jan 31 15:18:54 mydatalabvm systemd[1]: Starting Google Compute Engine Startup Scripts...
Jan 31 15:18:54 mydatalabvm startup-script[743]: INFO Starting startup scripts.
Jan 31 15:18:54 mydatalabvm startup-script[743]: INFO Found startup-script in metadata.
Jan 31 15:18:54 mydatalabvm startup-script[743]: INFO startup-script: Getting Docker credentials
Jan 31 15:18:55 mydatalabvm startup-script[743]: INFO startup-script: /home/datalab/.docker/config.json configured to use this credential helper
 for GCR registries
Jan 31 15:18:55 mydatalabvm startup-script[743]: INFO startup-script: Pulling latest image: gcr.io/cloud-datalab/datalab:latest
Jan 31 15:19:11 mydatalabvm startup-script[743]: INFO startup-script: Pulling repository gcr.io/cloud-datalab/datalab
Jan 31 15:19:11 mydatalabvm startup-script[743]: INFO startup-script: Error: Status 405 trying to pull repository cloud-datalab/datalab: "v1 Reg
istry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your im
age is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-no
tices"
Jan 31 15:19:11 mydatalabvm startup-script[743]: INFO startup-script: Trying to mount the persistent disk
Jan 31 15:19:11 mydatalabvm startup-script[743]: INFO startup-script: Creating /mnt/disks/datalab-pd/content/datalab
Jan 31 15:19:12 mydatalabvm startup-script[743]: INFO startup-script: mkswap: /mnt/disks/datalab-pd/swapfile: warning: wiping old swap signature
.
Jan 31 15:19:12 mydatalabvm startup-script[743]: INFO startup-script: Setting up swapspace version 1, size = 3.6 GiB (3885420544 bytes)
Jan 31 15:19:12 mydatalabvm startup-script[743]: INFO startup-script: no label, UUID=d538e8de-58d3-47d0-ac8f-847ce4c770ff
Jan 31 15:19:12 mydatalabvm startup-script[743]: INFO startup-script: sysctl: cannot stat /proc/sys/vm/disk_based_swap: No such file or directory


For the second command - here is the output:
mydatalabvm s_nasir # cat /var/log/startupscript.log | grep -i err
Jan 31 15:19:11 mydatalabvm startup-script[743]: INFO startup-script: Error: Status 405 trying to pull repository cloud-datalab/datalab: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices"

Do I need to enable Google Container Registry API?
Thanks -

**Comment by eilalan** [comment]
the default vm service account: XXXX-compute@developer.gserviceaccount.com take a look at the end of the #1928 ticket for exact steps

**Comment by datamiles** [comment]
No luck - I created the VM as me and I have am the project owner myself.

how do I find out the default service account for the VM? looks like I need to grant the default service account the permissions outlined in 1928.

thanks

**Comment by datamiles** [comment]
I also created a new VM - but same result. Please advise. Thanks

**Comment by harmon** [comment]
Sounds like your SSH key is password protected. Can you try adding ` /home/s_nasir/.ssh/google_compute_engine` to ssh-agent first?

Linux instructions:
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-linux

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-mac

**Comment by datamiles** [comment]
I followed the process listed here:

https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#platform-linux

I was able to set a passphrase while I was SSH'ed to VM via console.

when I try to connect to datalab from cloudshell - still no luck.

s_nasir@cpb100200300:~$ datalab connect mydatalabvm
Connecting to mydatalabvm.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-ke
ys
Waiting for Datalab to be reachable at http://localhost:8081/
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/
Enter passphrase for key '/home/s_nasir/.ssh/google_compute_engine':

Please advise. thanks

**Comment by datamiles** [comment]
Here is the output for firewalls rules from the cloudshell:

s_nasir@cpb100200300:~$ gcloud compute firewall-rules list
NAME                           NETWORK          DIRECTION  PRIORITY  ALLOW                         DENY
datalab-network-allow-ssh      datalab-network  INGRESS    1000      tcp:22
default-allow-dataproc-access  default          INGRESS    1000      tcp:8088,tcp:9870,tcp:8080
default-allow-icmp             default          INGRESS    65534     icmp
default-allow-internal         default          INGRESS    65534     tcp:0-65535,udp:0-65535,icmp
default-allow-rdp              default          INGRESS    65534     tcp:3389
default-allow-ssh              default          INGRESS    65534     tcp:22

just thought I share this.

**Comment by datamiles** [comment]
**here is the route list**

s_nasir@cpb100200300:~$ gcloud compute routes list
NAME                            NETWORK          DEST_RANGE     NEXT_HOP                  PRIORITY
default-internet                default          0.0.0.0/0      default-internet-gateway  1000
default-route-01ad27d1867b9f10  datalab-network  10.156.0.0/20                            1000
default-route-0ac14dfad85e2a38  default          10.164.0.0/20                            1000
default-route-275412a5bc3e42f6  default          10.132.0.0/20                            1000
default-route-2fbd0c8c366a9be0  default          10.160.0.0/20                            1000
default-route-36c1b4ebd795881a  datalab-network  10.138.0.0/20                            1000
default-route-36fde6a7464e863c  default          10.152.0.0/20                            1000
default-route-38535683fe5b9934  datalab-network  10.158.0.0/20                            1000
default-route-46af32089dd78de0  default          10.128.0.0/20                            1000
default-route-58eeb943aac6fac4  datalab-network  0.0.0.0/0      default-internet-gateway  1000
default-route-5a687f2261cae26e  default          0.0.0.0/0      default-internet-gateway  1000
default-route-72d99f3d39c7daa0  datalab-network  10.162.0.0/20                            1000
default-route-7c4a3ec9014e349e  datalab-network  10.148.0.0/20                            1000
default-route-7ecfe19f79326aeb  default          10.162.0.0/20                            1000
default-route-80fe4cbb5ec81e0d  datalab-network  10.142.0.0/20                            1000
default-route-8105c0b2d44d4917  datalab-network  10.132.0.0/20                            1000
default-route-8361e077d8f90578  datalab-network  10.146.0.0/20                            1000
default-route-8a317b4973db6e8a  default          10.156.0.0/20                            1000
default-route-8c8c00619de65850  datalab-network  10.150.0.0/20                            1000
default-route-8cc7c94d3b01840d  datalab-network  10.154.0.0/20                            1000
default-route-9bd199379a3ed598  default          10.138.0.0/20                            1000
default-route-9bfd1d5b8cdeda83  default          10.154.0.0/20                            1000
default-route-a3db4f5e6f2b2e55  datalab-network  10.164.0.0/20                            1000
default-route-aa3e56540fb186c5  default          10.158.0.0/20                            1000
default-route-c4dbb792d0d6548d  default          10.146.0.0/20                            1000
default-route-c5b62f57189ed75b  datalab-network  10.152.0.0/20                            1000
default-route-cdbc557591c20773  datalab-network  10.140.0.0/20                            1000
default-route-d88f683b9870f17e  default          10.142.0.0/20                            1000
default-route-d9c76a12c1bac473  default          10.150.0.0/20                            1000
default-route-dba2bbecaf2d30f2  default          10.140.0.0/20                            1000
default-route-e1cdd6c934207cfd  datalab-network  10.160.0.0/20                            1000
default-route-f60ccdd438d6ac9e  datalab-network  10.128.0.0/20                            1000
default-route-fcbb44d34448a072  default          10.148.0.0/20                            1000
s_nasir@cpb100200300:~$

**Comment by harmon** [comment]
Sorry, I totally misunderstood your original problem. I didn't catch that you were trying to do this via the Cloud Shell, I thought you were running this from your personal computer. So, based on that, the ssh key you setup in cloudshell has a password set to it. You need to either enter the correct password (did you write it down or store it in a password manager?), or generate a new SSH key for the cloudshell session. It's not a firewall issue, it keeps asking for a password, and it's not receiving the correct one.

So, one way is to remove your existing SSH key from your cloud shell session, and when you try and connect again, it'll generate a new one:

```
user@project-name: ~$ mv ~/.ssh/google_compute_engine ~/.ssh/google_compute_engine.old

user@project-name: ~$ mv ~/.ssh/google_compute_engine.pub ~/.ssh/google_compute_engine.old.pub

user@project-name: ~$ gcloud compute ssh mydatalabvm
WARNING: The public SSH key file for gcloud does not exist.
WARNING: The private SSH key file for gcloud does not exist.
WARNING: You do not have an SSH key for gcloud.
WARNING: SSH keygen will be executed to generate a key.
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /home/harmon/.ssh/google_compute_engine.
Your public key has been saved in /home/harmon/.ssh/google_compute_engine.pub.
The key fingerprint is:
SHA256:f7WFNbTa9Gs2BBKWeQhTLreMic harmon@cs-6000-devshell-vm-54asdf
The key's randomart image is:
+---[RSA 2048]----+
|        o++=o=*. |
|        oo+o+oo=.|
|       . . o   +o|
|        .  oo+Bo.|
|           o.+o+o|
|      . ..  =.+oo|
|       E  . .+.. |
|        =  .     |
|                 |
+----[SHA256]-----+
No zone specified. Using zone [us-east1-c] for instance: [harmon-test].
Updating project ssh metadata.../Updated [https://www.googleapis.com/compute/v1/projects/my-project].
Updating project ssh metadata...done.
Waiting for SSH key to propagate.
Enter passphrase for key '/home/harmon/.ssh/google_compute_engine':
Enter passphrase for key '/home/harmon/.ssh/google_compute_engine':
harmon@harmon-test ~ $
```

If you can ssh in via the cloud shell this way, your datalab connect *SHOULD* work.

**Comment by chmeyers** [comment]
I was investigating a similar issue to this last night, and it looks like it might be an issue with the propagation of the SSH keys.  It was only happening on the first Datalab VM that I created in a brand new project.  I'll ping back here when I have a better idea of the issue.

**Comment by datamiles** [comment]
that worked like a charm. thanks Harmon - you da man :)

**Comment by harmon** [comment]
:)

**Comment by EvilAngelPixie** [comment]
I've encountered a similar issue - I went to update datalab via:

`datalab delete --keep-disk [instance_name]
datalab create [instance_name] --zone [same_zone]`

And promptly got the following error:

`Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code `[255].` 

Can't connect via cloud console using `datalab connect`, or `gcloud compute ssh datalab@[instance-name]` via cloud console or terminal, but SSH via browser from VM menu connects.

Things I've checked:
- datalab container is running
- firewall rules appear to be ok
- refreshed ssh keys (tried this from both my work and home pcs)
- gcloud components update/reinstall run
- reset vm
- created fresh datalab vm with --disk-name [instance_name] (same issue)
- created fresh datalab vm after deleting all things datalab as per the documentation (same issue)

I downloaded copies of the notebooks I need, so at this stage I really just want to be able to spin up a datalab instance that lets me connect to it and get back to work, so any suggestions appreciated!

**Comment by harmon** [comment]
There should be a fix published in the next release for this issue. It's been fixed in this PR: https://github.com/googledatalab/datalab/pull/1937

To fix this on your instance, I would make sure /home/datalab is owned by datalab. It's probably owned by root:root right now.

So:

```
$ gcloud compute ssh your-instance-name
$you@your-instance-name ~: sudo chown datalab:datalab -R /home/datalab
```

See if that fixes it for you.

**Comment by harmon** [comment]
You can also try hitting "Reset" on your VM. See his comments here:

https://github.com/googledatalab/datalab/issues/1926#issuecomment-359900218

**Comment by EvilAngelPixie** [comment]
@harmon Thanks Adam - I had tried reset unsuccessfully earlier, but changing permissions worked!

**Comment by brilindquist** [comment]
I've been having a similar problem.  Sometimes I can connect to a VM using 'datalab connect', but not always.  The VM will become impossible to connect to via datalab, and then some time later (sometimes minutes later, sometimes hours later), I'll be able to connect again.

Here's the error message:

datalab  connect brilindquist-test-2
Connecting to brilindquist-test-2.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/

I can briefly connect via "gcloud compute ssh brilindquist-test-2 --zone=us-central1-b" but then I get disconnected a few seconds later:

gcloud compute ssh brilindquist-test-2 --zone=us-central1-b
brian_lindquist@brilindquist-test-2 ~ $ Connection to 35.193.52.63 closed by remote host.
Connection to 35.193.52.63 closed.
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].

I've tried:
mv ~/.ssh/google_compute_engine ~/.ssh/google_compute_engine.old
mv ~/.ssh/google_compute_engine.pub ~/.ssh/google_compute_engine.pub.old
and I've also tried resetting the VM.  Neither of these things fixes the problem.

Let me know if you have any ideas or requests for more information.

**Comment by ojarjur** [comment]
@brilindquist There's almost no chance that the issue you are seeing could be related to the issues described above; one was specific to a single user's setup and the other was related to a bad release that was fixed back in February.

Open a new issue for your report and add the following information:
1. Where you are running the `datalab connect` command (i.e. from Cloud Shell, directly from your workstation, etc).
2. What version of the Cloud SDK you have installed (i.e. the output of `gcloud version`).
3. Whether or not you can connect with the `SSH` button in the cloud console.
4. Whether or not you can SSH in as the `datalab` user (i.e. `gcloud compute ssh datalab@brilindquist-test-2`)

In the mean time, I will close this bug so that no one else sees it being open and confuses the issue they have with this one.

**Comment by yptheangel** [comment]
what worked for me, go to ssh folder and delete everything inside it and restart the ssh keygen process.
cd /home/<your_username>/.ssh/
rm *

**Comment by HeshamMahrous** [comment]
Hey guys I have the same problem but it is a little interesting than that, I cant even ssh the datalab instance through console ! I created the datalab myself from my terminal (Mac OS) using this command `datalab create hesh --verbosity=debug --subnet-name datalab-network` ('datalab create hesh' only doesnt work for me it throws me a subnet error)  

when I do `datalab connect hesh` it gives me a permission problem
Connecting to hesh.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
datalab@35.239.218.65: Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255]. 

Again I cant access the instance itself from my console by pressing the ssh button, 

Things i tried: 
1) Updated version to 214 using gcloud compoents update 
2) add my public key in the instance from console 
3) changing the format of keys to have [user]: ssh-rsa-[key] [user] as suggested in the materials. 

Can you guys please help I am very behind on my work and its been more than a week trying to figure out this problem thanks

**Comment by ojarjur** [comment]
@HeshamMahrous, you could be hitting #2014, which was fixed with version 215.0.0 of the Cloud SDK.

Try upgrading the Cloud SDK to version 215.0.0 and the delete and recreate your instance (passing the `--keep-disk` flag to the `datalab delete` command so that your notebooks disk is reused).

**Comment by HeshamMahrous** [comment]
Actually i made a mistake my version is 216

**Comment by HeshamMahrous** [comment]
but yeh i am actually familiar with #2014 that didnt work for me i am still stuck at the part when i cant even ssh from console even though i created the instance
