### ISSUE TITLE
"Notebook Changed" popup every save

### ISSUE THREAD

**Issue by andrenmo** [googledatalab/datalab#1938]
Every time a notebook is saved (automatically or manually) a popup appears saying that the file was modified since last save.
The Shared Driver option is enable on Docker and the files appear on the folder.
I am running a fresh install of the datalab docker image on windows, i used these instructions:
https://developers.google.com/earth-engine/python_install-datalab-local

Windows 10 (64)
Docker 17.12.0-ce, build c97c6d6
Image - gcr.io/earthengine-project/datalab-ee:latest

**Comment by andrenmo** [comment]
![screenshot-2018-2-5 untitled notebook](https://user-images.githubusercontent.com/23079130/35803891-a04526b2-0a5c-11e8-8b23-4de13eb81947.png)

**Comment by yebrahim** [comment]
Is there another process modifying the file? What does the shared driver option do?

**Comment by andrenmo** [comment]
No, the file is not modified by an external software, and the full driver was shared in "Shared Drivers" tab in Docker settings.

What I did to reproduce the bug:
1 ) Create a new container using these insctructions:
https://developers.google.com/earth-engine/python_install-datalab-local
2 ) Create a new file and save
3 ) Modify the file and save again

When trying to save the second time the warning popup appears.
The file was not modified between the two saves, according with Explorer.

**Comment by yebrahim** [comment]
This doesn't happen for me unless I have the file modified by another process. I tried the earth engine image but didn't see anything different.
Do you have two tabs open for this notebook by any chance? Or another user accessing the same notebook?

**Comment by andrenmo** [comment]
I tried again, with a clean install of the docker container and the the error occurs again, even if just one tab open.
I checked in PowerShell and the LastWriteTime didin't change since the previous save.
Because it's a corporate notebook I dont have full access to do a fresh install or stop all programs, maybe is a program that is conflicting with datalab.
Since you cannot reproduce and i dont have full control of the computer I believe that this bug can be marked as closed.

**Comment by yebrahim** [comment]
It's interesting because I'm running the same docker image you pointed out: EarthEngine, so there shouldn't be any differences inside the container. The only thing I can think of is that some other process on the host machine outside Docker is tampering with the directory you mounted (`${HOME}/workspace/datalab-ee` by the guide).

I'll close this, but feel free to continue the discussion if you want to look further into it.
