### ISSUE TITLE
Release 20180206 of the 'datalab' command line tool.

### ISSUE THREAD

**Issue by chmeyers** [googledatalab/datalab#1945]
This is a tracking issue for the 20180206 release of the datalab command line tool.

This issue will be used to report the source of the tool, it's changes, and when it is incorporated into the Google Cloud SDK

Source
The commit of the release is 85e301f9717124dab15b7196594d132766937c48
A tarball of the CLI tool release can be downloaded by running:

gsutil cp gs://cloud-datalab/builds/datalab-cli-85e301f9717124dab15b7196594d132766937c48.tgz ./
The following changes are included in this release:

Bug Fixes:
#1930: Disable os-login on newly created instances.
#1937: Ensure the 'datalab' user exists on newly created instances.
#1943: Fix for mounting multiple GPUs must each be mapped into a Container OS docker image.

**Comment by ojarjur** [comment]
This was included in the 189.0.0 release of the Cloud SDK
