### ISSUE TITLE
running datalab script on large dataset - a request for advice

### ISSUE THREAD

**Issue by eilalan** [googledatalab/datalab#1949]
Hi,

I have a datalab python code that was tested with small dataset.
I would like to execute the same code on a much larger dataset. What will be the recommended way to do so? I am looking for a process / tool that will run the datalab and adjust the resources of the machine as needed (CPU and memory).

I was looking into dataflow. Any advice if this is the simplest way for batch custom parsing with access to google storage?

Many thanks for any reference,
Eila

**Comment by harmon** [comment]
Sounds like you need to setup Kubernetes, which I believe can handle scaling mem/cpu in realtime for your docker container. Maybe look into Kubernetes Engine, although I haven't played with it. There's also Cloud Functions, which you can invoke with specific CPU/mem constraints. You can kick off a few of those instances to do multiprocessing on some data set in parallel.

**Comment by eilalan** [comment]
Thank you. Looking into Kubernetes and dataflow. will let you know what worked for me. Thanks, Eila

**Comment by nikhilk** [comment]
One way to accomplish your scenario might be to get a larger VM to run Datalab for the specific job... assuming you do not need scale out. Scale up is simpler, without requiring you to rework your code.

**Comment by eilalan** [comment]
Thanks. Thats exactly what I was doing. Still faced many issues with the data size, BigQuery max columns is 10K and pandas dataframe can not hold very large object. eventually I wrote the data to Big Query in slices and worked with datalab <-> BQ connection (not very fast). Thanks for the help. closing the issue.
