### ISSUE TITLE
Release 20180213 of the 'datalab' command line tool.

### ISSUE THREAD

**Issue by ojarjur** [googledatalab/datalab#1959]
This is a tracking issue for the 20180213 release of the datalab command line tool.

This issue will be used to report the source of the tool, it's changes, and when it is incorporated into the Google Cloud SDK

# Source
The commit of the release is 9ee598b4fdd29be1053ee984b79d74a7efe613d0
A tarball of the CLI tool release can be downloaded by running:

```sh
gsutil cp gs://cloud-datalab/builds/datalab-cli-9ee598b4fdd29be1053ee984b79d74a7efe613d0.tgz ./
```

The following changes are included in this release:

# New features:
#1951 Add a new `--diagnose-me` flag that can be used with any failing command to gather additional debugging information.
#1956 Add the ability to report which version of the tool was used to create a specific instance.
#1958 Add the ability to warn users if they are using a version with a known issue.
#1952 When running with the `--verbosity=debug` flag, if a nested gcloud command fails, then print the command that failed.

# Bug Fixes:
#1957 Fix a bug where sometimes the tool would exit with a message saying a gcloud command failed but would provide no other details.
#1950 Fix a bug where top level flags (e.g. `--project`, `--zone`, etc) were ignored if they came before the subcommand.

**Comment by chmeyers** [comment]
This was released as part of the 190.0.0 gcloud release.
