### ISSUE TITLE
GCS Backup Issue

### ISSUE THREAD

**Issue by harmon** [googledatalab/datalab#1960]
We noticed our /tmp directory inside the datalab docker instance filled up our persistent disk with gigs of "tmp.k3j4589/archive.zip" files. I tracked it down to GCSBackup.sh, which was successfully making a 40MB zip file each time it ran, but still output an error, causing the backup script to think it wasn't successful, and therefore it would run again, in a vicious cycle:

```
$ head /datalab/.backup_log.txt
20180211233656: Running GCS backup tool..
20180211233656: Running GCS backup tool..
20180211233656: Running GCS backup tool..
Failed creating the backup archive
Failed creating the backup archive
Failed creating the backup archive
20180211234655: Running GCS backup tool..
20180211234655: Running GCS backup tool..
20180211234655: Running GCS backup tool..
Failed creating the backup archive
Failed creating the backup archive
Failed creating the backup archive
20180211235655: Running GCS backup tool..
20180211235655: Running GCS backup tool..
20180211235655: Running GCS backup tool..
Failed creating the backup archive
Failed creating the backup archive
Failed creating the backup archive
20180212000655: Running GCS backup tool..
20180212000655: Running GCS backup tool..
20180212000655: Running GCS backup tool..
Failed creating the backup archive
```

I ran the zip command in verbose mode to see what was going on, and it seems to be the "forever" command's sock file that was throwing an error when trying to be read:

```
$ cd /content
$ zip -rv /tmp/wow.zip .
...
updating: .jupyter/	(in=0) (out=0) (stored 0%)
updating: .jupyter/nbconfig/	(in=0) (out=0) (stored 0%)
updating: .jupyter/nbconfig/notebook.json	(in=71) (out=61) (deflated 14%)
updating: .viminfo	(in=658) (out=308) (deflated 53%)
updating: .gitconfig	(in=120) (out=72) (deflated 40%)
  adding: .forever/sock/worker.15183916117837xa.sock
zip warning: No such device or address
	zip warning: could not open for reading: .forever/sock/worker.15183916117837xa.sock

zip warning: Not all files were readable
  files/entries read:  423 (133M bytes)  skipped:  1 (0 bytes)
total bytes=140321049, compressed=44816814 -> 68% savings
```

I'm going to disable auto-backups for now, but I thought I'd bring this to your attention.

Here's the culprit line: https://github.com/googledatalab/datalab/blob/master/containers/datalab/content/GCSbackup.sh#L144

Maybe exclude forever folder via:

```
zip -rq ${archive_name} "${backup_path}" -x *.forever*
```

**Comment by ojarjur** [comment]
That's an excellent analysis; thanks for digging in, and I'm sorry that this hit you.

I agree with your assessment. Additionally, we may want to add a trap that unconditionally deletes the temp file on exit.

**Comment by harmon** [comment]
Yeah, I think a trap like that would be a great idea.

**Comment by ojarjur** [comment]
@harmon I'll have a PR out to fix this soon.
