### ISSUE TITLE
Bad Request: Error 400 - When previewing on port 8081

### ISSUE THREAD

**Issue by kenwilly** [googledatalab/datalab#1962]
Datalab appears to be throwing this error today for multiple people across multiple projects when attempting to preview on port 8081.

**Comment by chmeyers** [comment]
Did you try it without using Cloud Shell?  Cloud Shell Web Preview proxies requests through appengine, which may be affected by an ongoing issue: https://status.cloud.google.com/incident/appengine/18003

**Comment by kenwilly** [comment]
I can't seem to find any documentation on how to access datalab without Cloud Shell.  Can you send a link over?

**Comment by chmeyers** [comment]
It's the same as from Cloud Shell, but you install the datalab command line tool locally.
https://cloud.google.com/datalab/docs/quickstart

Basically:
gcloud components update
gcloud components install datalab
datalab connect datalab-instance-name
Once it's connected, open http://localhost:8081 in a browser.

**Comment by kenwilly** [comment]
That did the trick.  Thanks
