### ISSUE TITLE
-bash: datalab: command not found

### ISSUE THREAD

**Issue by mushgrant** [googledatalab/datalab#1964]
Nothing seems to work with any datalab command. I've installed it. And when I try to install it again just to check it, says it's already there. 

~ > gcloud components install datalab
All components are up to date.

~ > datalab create new-notebook
-bash: datalab: command not found

Installed     │ Cloud Datalab Command Line Tool                      │ datalab                  │   < 1 MiB │

I was able to get it to work via the GUI and the google cloud shell
Curious why it wont work in bash. 

I have been able to create new projects, upload files to GCS, and access permissions via bash.

**Comment by harmon** [comment]
Double check your $PATH to make sure datalab is in one of those folders. You can use `gcloud info` to see where the executables are installed, and verify that it's PATH-ed correctly.
