### ISSUE TITLE
BigQuery API from datalab

### ISSUE THREAD

**Issue by eilalan** [googledatalab/datalab#1969]
I am writing a large data to BQ and have issues when the data is inserted to the table
```
expression data

expression = hdf['/data/']['expression']

expression.shape
(79318, 35238)

type(expression)
h5py._hl.dataset.Dataset

#### generate one row dataframe with columns names

#### dataframe for initialization
df_expression = pd.DataFrame(data = expression[1:5,:], columns=genes)

df_expression
4 rows × 35238 columns

#### BQ with column names (5 rows)
from datalab.context import Context
import datalab.storage as storage
import datalab.bigquery as bq

bigquery_dataset_name = 'archs4'
bigquery_table_name1 = 'human_expression'

# Define BigQuery dataset and table
dataset = bq.Dataset(bigquery_dataset_name)

# Create BigQuery dataset
if not dataset.exists():
    dataset.create()
	
# Create or overwrite the existing table if it exists
table1 = bq.Table(bigquery_dataset_name + '.' + bigquery_table_name1)

table_schema_1 = bq.Schema.from_dataframe(df_expression)

table1.create(schema=table_schema_1, overwrite = True)

```

table1.create(schema=table_schema_1, overwrite = True) fires the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/datalab/utils/_http.py in __init__(self, status, content)
     46     try:
---> 47       error = json.loads(content)['error']
     48       if 'errors' in error:

/usr/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    311         raise TypeError('the JSON object must be str, not {!r}'.format(
--> 312                             s.__class__.__name__))
    313     if s.startswith(u'\ufeff'):

TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-73-bbe5d3905c0b> in <module>()
----> 1 table1.create(schema=table_schema_1, overwrite = True)

/usr/local/lib/python3.5/dist-packages/datalab/bigquery/_table.py in create(self, schema, overwrite)
    223       Exception if the table couldn't be created or already exists and truncate was False.
    224     """
--> 225     if overwrite and self.exists():
    226       self.delete()
    227     if not isinstance(schema, _schema.Schema):

/usr/local/lib/python3.5/dist-packages/datalab/bigquery/_table.py in exists(self)
    189       raise e
    190     except Exception as e:
--> 191       raise e
    192     self._info = info
    193     return True

/usr/local/lib/python3.5/dist-packages/datalab/bigquery/_table.py in exists(self)
    183     """
    184     try:
--> 185       info = self._api.tables_get(self._name_parts)
    186     except datalab.utils.RequestException as e:
    187       if e.status == 404:

/usr/local/lib/python3.5/dist-packages/datalab/bigquery/_api.py in tables_get(self, table_name)
    357     """
    358     url = Api._ENDPOINT + (Api._TABLES_PATH % table_name)
--> 359     return datalab.utils.Http.request(url, credentials=self._credentials)
    360 
    361   def tables_list(self, dataset_name, max_results=0, page_token=None):

/usr/local/lib/python3.5/dist-packages/datalab/utils/_http.py in request(url, args, data, headers, method, credentials, raw_response, stats)
    153           return json.loads(str(content, encoding='UTF-8'))
    154       else:
--> 155         raise RequestException(response.status, content)
    156     except ValueError:
    157       raise Exception('Failed to process HTTP response.')

/usr/local/lib/python3.5/dist-packages/datalab/utils/_http.py in __init__(self, status, content)
     50       self.message += ': ' + error['message']
     51     except Exception:
---> 52       lines = content.split('\n') if isinstance(content, basestring) else []
     53       if lines:
     54         self.message += ': ' + lines[0]

TypeError: a bytes-like object is required, not 'str'
```
what is the error about?

I would like to upload all the expression data to BQ and was not able to do so simply by copying the data to BQ.
I initialize small pandas dataframe because pandas is unable to initialize large dataframe with all the expression data. this dataframe will be uploaded to BQ. any improvement for this walkaround?

Many thanks,
Eila

**Comment by eilalan** [comment]
I tried also from the pandas BQ interface and there I hit another issue:

`gbq.to_gbq(df_expression, tableName, 'orielresearch-xxx', chunksize=None, verbose=True, reauth=False, if_exists='replace', private_key=None, auth_local_webserver=False)`

ant there I have reached the columns threshold:
`GenericGBQException: Reason: 400 POST https://www.googleapis.com/bigquery/v2/projects/orielresearch-188115/datasets/archs4/tables: Too many total leaf fields: 35238`
35238 - is the number of columns...any way to work around this one? I might ask Google BigQuery to help me with that issue

Thanks,
Eila

**Comment by chmeyers** [comment]
The "TypeError: a bytes-like object is required, not 'str'" issue you ran into got fixed by: https://github.com/googledatalab/pydatalab/pull/671, which just went out in today's Datalab release.

However, we recommend switching from
import datalab.storage as storage
import datalab.bigquery as bq
to
import google.datalab.storage as storage
import google.datalab.bigquery as bq
as the "datalab" versions are deprecated and only the google.datalab versions get new features.

I don't know of any work around for the leaf fields limit.

**Comment by eilalan** [comment]
Thanks chmeyers, I have partitioned the data into 10K columns to solve the leaf issue.
This is really a common use case in genomics (which google are pursuing Google Genomics) and I wished that this limit was much higher or possible to set.
In any case, could you please help me with the followings:
- Can I update the datalab version on that machine?
- Is there a way to run the datalab cells without being connected to the web application during the the entire execution time

Many thanks,
Eila

**Comment by chmeyers** [comment]
You can follow these instructions to update the version of datalab on an existing instance: https://cloud.google.com/datalab/docs/how-to/lifecycle#updating_the_cloud_datalab_vm_without_deleting_the_notebooks_disk

Cells will continue to run if you disconnect (though you may want to turn off auto-shutdown which defaults to 90 minutes), but you won't be able to see the cell output so you'll want to send the output somewhere.

**Comment by eilalan** [comment]
Thanks. The output is going to bigquery but I would like to see which cell is being executed when I reconnect. Is this possible?
what is the shutdown idle mean? not using the UI or nothing is being executed on the machine?

Thanks again,
Eila
