### ISSUE TITLE
can not connect to kernel from datalab

### ISSUE THREAD

**Issue by eilalan** [googledatalab/datalab#1972]
Hello,

Please see the linke for the kernel issue: https://drive.google.com/file/d/19knBbbGSjdndHc8txS_a5NRb8pW8X0Bf/view?usp=sharing 
 - i cant get python 2 or python 3 attached.
This issues is on datalab with gcsfuse image that I was using for the last month with no issues.

I have created a new datalab + gcsfuse image with the latest datalab and there importing h5py was firing an error
`import h5py`

anything else is working.

Any idea what might be the issue for any of them.

Thanks,
Eila

**Comment by eilalan** [comment]
For the H5Py issue, here is the code:
`
!pip install h5py
Requirement already satisfied: h5py in /usr/local/envs/py2env/lib/python2.7/site-packages
Requirement already satisfied: numpy>=1.7 in /usr/local/envs/py2env/lib/python2.7/site-packages (from h5py)
Requirement already satisfied: six in /usr/local/envs/py2env/lib/python2.7/site-packages (from h5py)

import h5py
ImportErrorTraceback (most recent call last)
<ipython-input-11-c9f0b8c65221> in <module>()
----> 1 import h5py

/usr/local/envs/py2env/lib/python2.7/site-packages/h5py/__init__.py in <module>()
     24 # We tried working around this by using "package_dir" but that breaks Cython.
     25 try:
---> 26     from . import _errors
     27 except ImportError:
     28     import os.path as _op

ImportError: cannot import name _errors
`
any idea what is the issue?
Thanks,
Eila

**Comment by chmeyers** [comment]
The h5py thing will be fixed by https://github.com/googledatalab/datalab/pull/1971

Until then:
!pip install h5py --upgrade --force-reinstall
Followed by resetting the session (to pick up the new import) worked for me.

**Comment by eilalan** [comment]
Thank you. I was able to work with h5py. 
I don't know where to report on that. Connecting to datalab during the weekend was challenging. The Google Cloud Platform status looks good but connecting to local host yield: 504 Gateway Time-out many times during the weekend.
Thanks for your help,
Eila

**Comment by rileyjbauer** [comment]
This issue seems to have been addressed. Please reopen if you are still experiencing issues connecting to the kernels
