### ISSUE TITLE
jupyter and nbconvert can not be run outside notebooks

### ISSUE THREAD

**Issue by HaipengSu** [googledatalab/datalab#1978]
I normally use crontab to schedule a lot of jobs running notebooks, for example,

`*/5 * * * * docker exec $(docker ps) jupyter nbconvert --ExecutePreprocessor.timeout=200 --execute /content/test.ipynb`

However, after updating Datalab to the latest version, all my scheduled jobs failed. and I got the following error:

`rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"exec: \\\"jupyter\\\": executable file not found in $PATH\"\n"`

![image](https://user-images.githubusercontent.com/13719899/37412575-8d4ef632-277b-11e8-86fa-daf3c812ccf6.png)

when I switch back to an older version of Datalab (backup on my local machine), I can run the job again. 
Is that means package <b>jupyter</b> and <b>nbconvert</b> are not available in the latest version any more?

By the way, my docker version is shown below:

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by HaipengSu** [comment]
Case update.

I tried inside notebook, and jupyter and nbconvert works well. But still, outside notebook even inside my container, it is still not working. 

![image](https://user-images.githubusercontent.com/13719899/37483810-25897c60-285d-11e8-99d2-800489c44a24.png)

![image](https://user-images.githubusercontent.com/13719899/37484344-a6e6738e-285e-11e8-9bd8-edb3796a89e9.png)

any ideas?

**Comment by rileyjbauer** [comment]
This looks like it was probably caused by the migration to Conda.

Jupyter is no longer available outside of the Conda environments, but if you switch to one using:
`source activate py2env`
or
`source activate py3env`
then I believe your above commands will work.

**Comment by HaipengSu** [comment]
Thx, @rileyjbauer, that was helpful. inside container, i can active py2env and use jupyter & nbconvert, however, it won't load py2env outside of the container when using command,

`docker exec datalab jupyter nbconvert /content/test.ipynb`

When checking the conda env inside my datalab container, I have 
![image](https://user-images.githubusercontent.com/13719899/37491392-12af8bd6-2874-11e8-9186-1e87fc2b816c.png)

Is that means conda env does refer to py2env but when execute the docker containers, it doesn't load the conda env? 

When checking in the previous version of datalab, I have 
![image](https://user-images.githubusercontent.com/13719899/37491497-753c82d6-2874-11e8-9bce-1ab4df8a0a00.png)

it seems the access points are different. I am not sure whether it makes a difference.

**Comment by rileyjbauer** [comment]
Ah, I see. Yes, the container doesn't automatically pick one of the custom Conda envs (py2env, py3env) so any exec command will execute in the default root env, which is something we may want to look into.

You can get around this though using something like:

`docker exec datalab bash -c "source activate py2env && jupyter nbconvert /content/test.ipynb"`

**Comment by HaipengSu** [comment]
@rileyjbauer Thx for looking into this.

**Comment by rileyjbauer** [comment]
No trouble! Thanks for raising the issue

**Comment by HaipengSu** [comment]
@rileyjbauer is there further action on this?

**Comment by rileyjbauer** [comment]
Unfortunately not at this time; interacting with Datalab through `docker exec` is not an officially supported part of this project.
Pull requests are always welcome though!

**Comment by HaipengSu** [comment]
@rileyjbauer OK. thx for the update.

**Comment by HaipengSu** [comment]
@rileyjbauer,  After updating to the newest version, even setting the environments path won' t work.  Ant thought?
Thanks
![image](https://user-images.githubusercontent.com/13719899/40013387-63bb0a9c-577b-11e8-91d9-c2ef371ed817.png)

**Comment by ojarjur** [comment]
@HaipengSu Does it work if you use `py3env` instead of `py2env`?

We do almost the exact same thing as part of our release process (see the test script [here](https://github.com/googledatalab/notebooks/blob/master/.test.sh#L111) ), but we use the Python 3 environment instead of the Python 2 one.

Note that this does not require the notebooks to be written in Python 3; the Python 3 environment still has support for launching Python 2 kernels.

I did not think Jupyter was installed in our Python 2 environment, so hopefully switching to the py3env will fix the issue..

**Comment by HaipengSu** [comment]
@ojarjur , I tried py3env, the kernel is fine, but it brings up Google Credentials. BTW, I am running datalab locally instead of on Google Cloud.

![image](https://user-images.githubusercontent.com/13719899/40017477-7f3ee78c-5787-11e8-8781-9f23f5b0de81.png)

the notebook is simple,
![image](https://user-images.githubusercontent.com/13719899/40018309-e5550a36-5789-11e8-9c27-1cc9fe29c602.png)

**Comment by ojarjur** [comment]
@HaipengSu Were credentials not required previously? I would expect them to be required by BigQuery.

Does it work if you do set up the credentials?

**Comment by HaipengSu** [comment]
@ojarjur 
Rolled back to the previous version, and it also needs the credential setup. 
Then, I switched back to the current version, setup the credential inside the container, and it works.(both py2env and py3env, not sure why the kernel works for py2env too)
![image](https://user-images.githubusercontent.com/13719899/40059906-4ab24170-5823-11e8-8676-2e6c0aaef060.png)

however, outside the datalab container, if I ran 
`docker exec datalab bash -c "source activate py2env && jupyter nbconvert --execute /content/Automotive/testNotebook.ipynb"`

the **DefaultCredentialsError** happens again, which confuses me.

**Comment by HaipengSu** [comment]
@ojarjur Then, I tries datalab on Google Cloud, it start works again. I suppose Google VM has the right setup on app Credentials but not my local machine.

**Comment by ojarjur** [comment]
@HaipengSu yes, when running in a VM, the container can pick up the credentials from the VM.

Did you set the credential by setting the environment variable, or by running a `gcloud` command?

If it was by setting a variable, then I suspect the reason your `docker exec` command failed to see the credential would be it having a different environment than the shell you were running inside the container. You can make them consistent by setting the environment variable using the `-e GOOGLE_APPLICATION_CREDENTIALS=...` option to the `docker run` command.
