### ISSUE TITLE
Typescript errors in local build

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#1981]
Hello,

I encountered the following typescript errors when trying to build Datalab locally. 

```
notebook.ts(176,5): error TS2531: Object is possibly 'null'.
test/settings-manager-test.ts(58,11): error TS2721: Cannot invoke an object which is possibly 'null'.
```

I used changes in the following branch to resolve the issue:
https://github.com/parthea/datalab/commit/282f1e3087f10ce2ebb2608bea7975845e8cac7b

**Comment by ojarjur** [comment]
I think we hit these kinds of issues periodically if Typescript updates and the newer version catches more bugs than the previous version did.

Please send out a PR with your change and I will happily merge it.

**Comment by parthea** [comment]
Thanks for the quick reply, @ojarjur ! I've opened PR #1982 .
