### ISSUE TITLE
google-cloud-dataflow and apach-beam libraries

### ISSUE THREAD

**Issue by eilalan** [googledatalab/datalab#1984]
Hello,

Is it possible to have datalab with the latest versions of dataflow and apache-beam.
The new dataflow has a direct runner that is 15 times faster and additional new features.
when I run pip update command, the libraries modules for apache-beam are not recognized by the import command.

Please advice.

Many thanks in advance,
Eila

**Comment by rileyjbauer** [comment]
Hello!

This should be fixed as of #2083 and will be in the next release.

Thank you for raising this!
