### ISSUE TITLE
Error on CLI when connecting to / creating a datalab

### ISSUE THREAD

**Issue by OrielResearchCure** [googledatalab/datalab#2009]
Hello,

I am trying to connect to a datalab that I was working on lately and getting the message:

`
datalab connect oriel-beam
You are using the Datalab CLI version "20180412", which has the following known issues:
        GPU instances fail to install the NVIDIA driver, preventing them from starting. The root cause was pinning to an older version of th
e driver that is no longer supported by Container Optimized OS. The issue is fixed in versions 20180503 or later. Alternatively, you can run
 the tool from the open source repository here: https://github.com/googledatalab/datalab/tree/master/tools/cli
Connecting to oriel-beam.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs
/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
`

What command should i run to be able to connect to the datalab. I have code there that I would like to access.

Many thanks for any help,
Eila

**Comment by OrielResearchCure** [comment]
working now

**Comment by developmentsme** [comment]
I'm facing the same issue. Not able to connect to datalab when attached with GPU.

**Comment by RD1991** [comment]
I'm facing same issue. Not able to connect to datalab when attached to gpu.
