### ISSUE TITLE
removing/disabling " --no-user-checking" 

### ISSUE THREAD

**Issue by magicomajid** [googledatalab/datalab#2020]
We use datalab in GCP and the parameter " **--no-user-checking**" created many security problems for us. 
I have tried to modify the datalab image following this [link ](https://github.com/googledatalab/datalab/wiki/Getting-Started)  and changing the file "[connect.py](https://github.com/googledatalab/datalab/blob/master/tools/cli/commands/connect.py)" to remove this paramater, but after i have pushed the image and created new datalab instance from cloud shell using "--image-name", when i try to connect to the vm still the parameter " --no-user-checking"  is working!
for our project we urgently need to remove or disable this parameter. how we can do it in GCP for all our instances? 
thanks

**Comment by ojarjur** [comment]
The CLI user checking is not a security barrier; it is merely meant to prevent accidentally sharing an instance and producing conflicting changes.

If you want to isolate individual instances to specific users, then use GCP's support for restricting SSH access. In particular:

1. Do not grant those users editor permissions on the project. All they need is the instance admin role.
2. Create a different service account for each user, and grant only that user the service account user role on the service account.
3. Create each user's instances with their corresponding service account.

**Comment by magicomajid** [comment]
Basicly we need to trace all the queries from the BigQuery that will be done from datalab's notebook by all users for security reasons.
In particular we did:
1.Do not grant those users editor permissions on the project. All they need is the instance admin role.
2.Create a different service account for each user, and grant only that user the service account user role on the service account.
3. Create each user's instances with their corresponding service account.

And this was ok for Data scientists users, but still project owners and projects Editors can use the Datalab VM of another user and make query from the BQ and in logging we see the service account of that user without finding that project owner did that query.
So the only way for us is to disable the parameter " --no-user-checking"  so even Project Owner can not connect to datalab Vm of other users.
That's why I have tried to modify the datalab image following this link and changing the file "connect.py" to remove this paramater, but after i have pushed the image and created new datalab instance from cloud shell using "--image-name", when i try to connect to the vm still the parameter " --no-user-checking" is working!
for our project we urgently need to remove or disable this parameter. how we can do it in GCP for all our instances?
This is very important for our client to trace the queries and i hope you provide us a solution.
Is there any possibility to disable this parameter ?
thanks

**Comment by magicomajid** [comment]
@ojarjur you are right about the direct SSH to the VM, but by removing the  "--no-user-checking" flag they can not use the notebook of the user. besides the project owner can ssh but they can not make a query as there is not GCloud SDK installed and they don't have access to notebook. 
In any project exists at least one project owner, what we need is to log who makes query in BQ, and understand if project owner makes a query using the VM of others.
I know that my question and what we want to do is very specific case, but i hope you kindly help me with a solution.

**Comment by ojarjur** [comment]
>  by removing the "--no-user-checking" flag they can not use the notebook of the user.

That's not correct. Anyone who can SSH in to the VM can access the Datalab UI. In fact, all that `datalab connect` does is ensure that the instance is running, and then SSH in to it.

> besides the project owner can ssh but they can not make a query as there is not GCloud SDK installed and they don't have access to notebook.

This is also not correct. Anyone who can get in to the VM can get the service account credentials from that VM and then use those credentials to issue queries to BQ.

> what we need is to log who makes query in BQ, and understand if project owner makes a query using the VM of others.

That is not possible. All that you can tell about queries coming from a VM is that they came from a VM with that service account. You cannot tell who or what issued the query from that VM.

Further, you cannot track who creates an SSH connection in to a VM.

> I know that my question and what we want to do is very specific case, but i hope you kindly help me with a solution.

The only thing you can do is limit the number of owners of the project (and any organization that owns the project). Anyone with ownership permissions over the project, including any org owners, can perform arbitrary actions as any of the project's service accounts.
