### ISSUE TITLE
How to update to the latest version

### ISSUE THREAD

**Issue by rtadewald** [googledatalab/datalab#2024]
I'm trying to se the new `--subnet` parameter. I've used `gcloud components update`, but using datalab create --subnet ... keeps me returning "unknow method"...

**Comment by ojarjur** [comment]
The feature to add the `--subnet` parameter has been submitted to the codebase, but not yet released.

It will be included in the next release of the CLI. Those releases are tracked with GitHub issues that have [the label `cli-release`](https://github.com/googledatalab/datalab/labels/cli-release).

Once a new CLI release goes out, you will be able to get it by updating your installation of the Cloud SDK.

Until then, you can use the feature by running the tool directly from source. It is in this repository at `tools/cli/datalab.py`.
