### ISSUE TITLE
No connection to datalab - any known issue? Google cloud looks healthy 

### ISSUE THREAD

**Issue by OrielResearchCure** [googledatalab/datalab#2047]
Hello, 

The scenario is the following 

```
datalab connect oriel-beam
Connecting to oriel-beam.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
```

The waiting is 'forever'. Do you see any issue that I need to check or is it a temporary issue?

Thanks,
eilalan

**Comment by ojarjur** [comment]
You are most likely hitting one of either #2051 or #2014 

A fix for the first will be included in the next release of the Cloud SDK, and I am putting together a fix for the second right now (I don't know yet when it will get released).
