### ISSUE TITLE
HELP - unable to connect to new or existing datalab machine since yesterday

### ISSUE THREAD

**Issue by OrielResearchCure** [googledatalab/datalab#2050]
Hello,
Connecting to an available machine is stack at the waiting for datalab to be reachable at http://localhost:8081/ ...

```
datalab connect oriel-beam
Connecting to oriel-beam.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/addi
ng-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/

```

Creating a new machine:
`datalab create datalab-check`
datalab was created...

Do you still want to use this network? (y/[n]): y
```
Creating the disk datalab-check-pd
Creating the instance datalab-check
Created [https://www.googleapis.com/compute/v1/projects/orielresearch-188115/zones/us-west2-c/instances/datalab-check].
Connecting to datalab-check.
This will create an SSH tunnel and may prompt you to create an rsa key pair. To manage these keys, see https://cloud.google.com/compute/docs/instances/addi
ng-removing-ssh-keys
Waiting for Datalab to be reachable at http://localhost:8081/
Permission denied (publickey).
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
Connection broken
Attempting to reconnect...
Waiting for Datalab to be reachable at http://localhost:8081/
```

What has changed? this is a big work stopper for me

Thank you for any reply.
eilalan

**Comment by OrielResearchCure** [comment]
update:
I was able to ssh to the new datalab machine.
I was NOT able to ssh to the old datalab machine.
I am fine moving to a new machine as long as I can copy the notebooks from the old machine. Can I use gsutil on the old machine to copy the notebook folder?
Thanks,
Eila

**Comment by OrielResearchCure** [comment]
After ssh-ing to to the machine, I was able to connect to the new machine. the old machine is stuck on transferring ssh keys to vm. 
All done on chrome using the ssh button on next to the machine name.

anyway suggestion how to retrieve the notebooks?

**Comment by OrielResearchCure** [comment]
solved. created a new machine with the same disk
datalab delete instance --keep-desk
datalab create instance (the same one as the deleted)

**Comment by XiaoxiaLin** [comment]
There is a typo, it should be: 
> datalab delete instance --keep-disk
