### ISSUE TITLE
Errors upon installing system packages

### ISSUE THREAD

**Issue by SoroushKadineh** [googledatalab/datalab#2072]
I am trying to run the following commands in order to install Turi Create eventually:
```
! apt update
! apt-get install -y libblas3 liblapack3 libstdc++6 python-setuptools
```
The following is the output:

> Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB] 
> Get:2 http://ftp.us.debian.org/debian testing InRelease [150 kB]               
> Err:1 http://security.ubuntu.com/ubuntu xenial-security InReleaseeate tempfiles for splitting up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_xenial-security_InRelease
>   Could not execute 'apt-key' to verify signature (is gnupg installed?)
> Err:2 http://ftp.us.debian.org/debian testing InReleaseouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/ftp.us.debian.org_debian_dists_testing_InRelease
>   Could not execute 'apt-key' to verify signature (is gnupg installed?)
> Get:3 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
> Err:3 http://archive.ubuntu.com/ubuntu xenial InReleasees for splitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial_InRelease
>   Could not execute 'apt-key' to verify signature (is gnupg installed?)
> Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
> Err:4 http://archive.ubuntu.com/ubuntu xenial-updates InReleaseplitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease
>   Could not execute 'apt-key' to verify signature (is gnupg installed?)
> Get:5 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
> Err:5 http://archive.ubuntu.com/ubuntu xenial-backports InReleaseitting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-backports_InRelease
>   Could not execute 'apt-key' to verify signature (is gnupg installed?)
> Reading package lists... Done
> W: GPG error: http://security.ubuntu.com/ubuntu xenial-security InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
> E: The repository 'http://security.ubuntu.com/ubuntu xenial-security InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: GPG error: http://ftp.us.debian.org/debian testing InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
> E: The repository 'http://ftp.us.debian.org/debian testing InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
> E: The repository 'http://archive.ubuntu.com/ubuntu xenial InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: GPG error: http://archive.ubuntu.com/ubuntu xenial-updates InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
> E: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> W: GPG error: http://archive.ubuntu.com/ubuntu xenial-backports InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
> E: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> E: Unable to locate package libblas3
> E: Unable to locate package liblapack3
> E: Unable to locate package python-setuptools

How can I get rid of these errors?

**Comment by ojarjur** [comment]
It looks like the assorted `apt` commands switch to a special user and then run the command.

Those commands then use the `/tmp` directory as part of their work, and our `/tmp` directory is set up so that only the `root` user (which is who the notebooks run as) has write permissions.

Thus, running the following in a code cell fixed the issue (for me):

```
!chmod a+rwx /tmp
```

I think that we should probably change the default permissions of the `/tmp` directory to be writeable by all accounts in the container.

**Comment by SoroushKadineh** [comment]
@ojarjur - Thanks, everything works now!
