### ISSUE TITLE
Jump to file search box not functional

### ISSUE THREAD

**Issue by domloong** [googledatalab/datalab#2073]
Since the latest datalab update, the search box in the main datalab page does not seem to be working anymore. Will there be a fix for this and is there a way to workaround this issue?

![image](https://user-images.githubusercontent.com/22451469/44916975-01b6d080-ad05-11e8-9109-df85191d2ac2.png)

**Comment by yebrahim** [comment]
This seems to be a regression from [this change](https://github.com/googledatalab/datalab/commit/a33ff751a9fac3a7c99f9ddc51e49e94c4d62ef2#diff-3e01c3ba5fda4d58f1a96454bf6619b4L154). We need to put back the jquery-ui import, which is needed to load the autocomplete functionality.
