### ISSUE TITLE
HOW to install PIL pyhton-package in datalab

### ISSUE THREAD

**Issue by aierfulz2016** [googledatalab/datalab#2086]
![image](https://user-images.githubusercontent.com/18022949/47293412-a89c5680-d63c-11e8-9b0b-d16c02663743.png)
I am using  datalab to learn Google Earth Engine in Google Cloud Platform(GCP). it is convenient to run python code in the cloud. It's fantastic. but now. I made a mistake  when I imported mapclient from ee. how can I do to solver the problem(specifically I need the PIL library in datalab)?

**Comment by yebrahim** [comment]
The [Earth Engine docs](https://developers.google.com/earth-engine/python_install-datalab-gcp#creating-a-custom-datalab-container) mention using a custom Datalab image, did you use that custom image or a vanilla Datalab image?

**Comment by aierfulz2016** [comment]
> The [Earth Engine docs](https://developers.google.com/earth-engine/python_install-datalab-gcp#creating-a-custom-datalab-container) mention using a custom Datalab image, did you use that custom image or a vanilla Datalab image?
[](url)
thank you for your reply. I am learning it just now and saw it from docs for datalab. thank you a lot, I will try agian.

**Comment by yebrahim** [comment]
Sure thing. I'll close this since there's no action required here.
