### ISSUE TITLE
Build a different image using Datalab create command

### ISSUE THREAD

**Issue by aaryapatel007** [googledatalab/datalab#2088]
How do I create an Intel® optimized Deep Learning Image: TensorFlow 1.12.0 m11 (with Intel® MKL-DNN/MKL and CUDA 10.0) Image using Datalab create command?

**Comment by yebrahim** [comment]
You can create your image separately (see an [example here](https://github.com/googledatalab/datalab/blob/6f1a5b4877ee475406d5661c42dfcd6a60b582b9/containers/datalab/Dockerfile-extended-example.in)), upload it to a GCR bucket in your project, then create a datalab instance using that image: `datalab create my-instance --image-name gcr.io/myproject/myimage`.
