### ISSUE TITLE
Notebook can consistently shut down the autosave feature -- work cannot be saved

### ISSUE THREAD

**Issue by brianchunkang** [googledatalab/datalab#2108]
The execution of the attached notebook in datalab can consistently kill the autosave function. No work can be saved after the execution of the last cell. Notebook attached.

Here the same error happening on Jupyter Notebooks referenced on their github site: [https://github.com/yuvipanda/jupyterhub-nginx-chp/issues/17]

The Jupyter Notebooks issue submitter worked around this by updating the client_max_body_size on their nginx server. Is there a way to update something similar on the datalab source repository?

[autosave_failed_example.zip](https://github.com/googledatalab/datalab/files/2700960/autosave_failed_example.zip)

**Comment by janpeuker** [comment]
Just wondering, do you see an HTTP 413 fro nginx? If that's the case, are you maybe running from Cloud Shell in which case the solution might be in #2106 ?

**Comment by janpeuker** [comment]
I suggest to close this, too?

**Comment by brianchunkang** [comment]
Yes, please do.
