### ISSUE TITLE
Feature: User should be able to load Python packages in Datalab container

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#463]
This has come up multiple times in discussions with internal and external customers and usability study:
Users want to load Python packages they use in a way that survives container restarts. We had discussed some sort of "profile file" to load packages through standard means (e.g. pip install) upon startup. A trans-container, declarative mechanism would be needed in general.

Current in-notebook workaround is as shown in this example:
%%bash 
pip install bokeh

**Comment by VelizarVESSELINOV** [comment]
:+1:

**Comment by Di-Ku** [comment]
@parthea has already built an extension mechanism that _could_ be used but that required container rebuild. I would prefer providing a lighter weight mechanism such as a shell script that is run on container startup. It does have the downside of increasing startup time but the tradeoff is well worth it to avoid having to clone / pull and rebuild.
@gramster has a reasonable mechanism that I prefer for this purpose - drop a startup.sh (or something similar) file in your ~/datalab/ directory and let the container pick it up on startup. If you make a mistake, the iteration is pretty short.

**Comment by nikhilk** [comment]
In addition to startup.sh, we should make derived containers more first class -- but do so by showing how people can author their own _Dockerfile_ and run docker build. #826 does something along those lines, but tells people to author something other than a Dockerfile... we should simply use existing docker mechanisms IMO.

**Comment by parthea** [comment]
> #826 does something along those lines, but tells people to author something other than a Dockerfile

@nikhilk  In #828, users can already create a file called `containers/datalab/Dockerfile-extended.in` which is already a Dockerfile . This will be used to generate derived container. Please let me know if this addresses the concern. I am happy to submit another PR to make the process easy for users. To clarify, #828 also provides users with the option of creating a file called `containers/datalab/custom-packages.txt` which is a requirements.txt file.

> In addition to startup.sh, we should make derived containers more first class -- but do so by showing how people can author their own Dockerfile and run docker build.

The file called  `containers/datalab/Dockerfile-extended.in` already provides a good starting point for users to create their own Dockerfile. Perhaps, the next step is to create a PR to update the existing documentation? Please confirm.

I am also interested to submit a PR for the new feature requested which is to add a file called `startup.sh` that runs at start up (if it exists).

**Comment by nikhilk** [comment]
@parthea thanks for contributing that. Its definitely a step in the right direction.

Consider the following for the next step -- defining/building/running extended containers shouldn't require cloning the datalab repo, or understanding the dev workflows within the repo. In other words, extending and creating derived containers should be a datalab end-user feature. It might be just documentation or a sample of just a Dockerfile that looks like the following:

    FROM gcr.io/cloud-datalab/datalab:latest
    sudo pip install xyz

and a script to build this and run it.

**Comment by gramster** [comment]
If the latter, then perhaps just a wiki entry? Although before we do that
we should probably push a new container with a different path/tag, as the
datalab:latest is the managed VM container. I had pushed a datalab:local a
while back; I could do an update of that. Or maybe we could use
gcr.io/cloud-datalab/datalab-local:latest.

**Comment by parthea** [comment]
I can provide instructions in the wiki, as well as a sample script for users to create a derived docker container. How do I go about requesting revisions to the [Datalab Getting Started Wiki](https://github.com/googlecloudplatform/datalab/wiki/Getting-Started)? Is there a repo on github.com?

**Comment by ojarjur** [comment]
Our recommended solution to this is now documented here: https://cloud.google.com/datalab/docs/how-to/adding-libraries
