### ISSUE TITLE
Parameterized queries in Python cell don't seem to work: "Unsatisfied dependency"

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#465]
%%sql --name analysis

log = table(offset='-1y,-1m,-21d', format='cloud-datalab:sampledata.requestlogs_%Y%m%d')
endpt = 'Other'
status = 400

DEFINE QUERY quantile_data
SELECT status, hour(timestamp) h, count(*) 
  FROM $log
    WHERE endpoint = $endpt and status > $status
    GROUP BY status, endpoint, h
    ORDER BY status, h

---- In another cell ---
log = bq.table('cloud-datalab:sampledata.requestlogs_20140616')
df = bq.query(analysis.quantile_data).to_dataframe()

Result
Exception: Unsatisfied dependency $log

Expected: a way to use a parameterized query in Python block

**Comment by gtkirankumar31** [comment]
For me its not working,

in 1st cell,

%%sql --module qname
app_name='XXX'

SELECT app_name , count(id) as c
FROM table_data
where app_name=$app_name

----in next cell--
bq.Query(qname).to_dataframe()

I get the desired output.
----in next cell---
%%sql --module qname1
SELECT app_name , count(id) as c
FROM table_data
where app_name=$app_name

----in next cell---
bq.Query(qname1).to_dataframe()

now I get unsatisfied dependency
I can't use the values defined in previous cells
why?

**Comment by parthea** [comment]
The following may work:

```
----in next cell---
app_name='XXX'

----in next cell---
%%sql --module qname
SELECT app_name , count(id) as c
FROM table_data
where app_name=$app_name

----in next cell---
bq.Query(qname, app_name=app_name).to_dataframe()


----in next cell---
%%sql --module qname1
SELECT app_name , count(id) as c
FROM table_data
where app_name=$app_name

----in next cell---
bq.Query(qname1, app_name=app_name).to_dataframe()

```

In the future, please post questions on stackoverflow under the tag `google-cloud-datalab`

http://stackoverflow.com/questions/tagged/google-cloud-datalab

**Comment by gtkirankumar31** [comment]
thanks.. now its working

**Comment by gramster** [comment]
Each SQL cell is like a separate Python module. Furthermore, the
'variables' aren't really variables, they are used to create an argparse
argument parser associated with the module. So you need to define the value
for the second query; there is no default otherwise.

**Comment by gtkirankumar31** [comment]
thank u gramster..
