### ISSUE TITLE
Socket.io connections result in "Waiting for connections"

### ISSUE THREAD

**Issue by nikhilk** [googledatalab/datalab#475]
Apparently a result of the over-aggressive socket.io polling, resulting in this error when hitting more than 6 open tabs.

Possibly interesting references:

http://stackoverflow.com/questions/17298950/socket-io-not-working-in-chrome-and-firefox-on-windows
http://stackoverflow.com/questions/30250915/polling-interval-for-xhr-for-socket-io-1-0

**Comment by gramster** [comment]
Obsolete?

**Comment by chmeyers** [comment]
Closing as obsolete
