### ISSUE TITLE
Need to create bucket in Datalab setup for sample log data

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#486]
Currently "BigQuery - Extracting Data" fails for all projects that didn't have an older version of Datalab installed (i.e. for most projects in the world). Chris ran into this when he did a test drive of 8/24 alpha drop.

Along with the <project name>-datalab bucket, need to create <project name>-datalab-data bucket (need to check name length etc)

**Comment by gramster** [comment]
I think this is obsolete?
