### ISSUE TITLE
Add schema validation for chart data

### ISSUE THREAD

**Issue by gramster** [googledatalab/datalab#530]
The Google Chart API docs include the required data format for each type of chart. We should build a simple validator that can report schema issues before attempting to draw a chart so we can give meaningful errors in this case.

**Comment by yebrahim** [comment]
I added a [naive schema validator](https://github.com/googledatalab/pydatalab/blob/035a4a5a0abd17826e0af62b4cbfe87e21d5f771/google/datalab/utils/commands/_utils.py#L81) when getting the field list for charting, I think this is enough for this use case.
