### ISSUE TITLE
Table viewer fails to page ("Busy" for a very long time)

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#548]
This is for the latest alpha candidate:
In "BigQuery - JavaScript UDFs", after successful (re-)execution, tried to go to the second page of the table viewer (25 of 100 rows shown on first page).

Expected:
Second page within reasonable amount of time

Actual:
Second page failed to load even after ~4 min. Browser page reload worked but clicking again on second page of the table viewer resulted in the same exact behavior. Same behavior even after re-execution.

Ruled out:
Suspected out-of-memory condition on the MVM but that wasn't the case. I was able to open and run more notebooks without any issue.

**Comment by gramster** [comment]
Obsolete?

**Comment by yebrahim** [comment]
Closing as obsolete. Please reopen if it shows up again.
