### ISSUE TITLE
SQL parameters for use in notebook could be and should be simpler

### ISSUE THREAD

**Issue by Di-Ku** [googledatalab/datalab#656]
For many workflows, I need to define simple parameters like table name in one place (say table = ...) and use them in the following cells in the form $module_name.table.
We seem to have lost this ability. Logging for tracking this. Likely needs an offline discussion for quicker/better resolution.

**Comment by gramster** [comment]
We haver never had this ability. Only queries could be referenced across cells, as they define named entities in the module's namespace. Parameters do not; they define variables that are used transiently to create an argparse for the queries.

If we wanted to support this we would need to have parameters define long-lived entities in the module namespace, which is certainly possible, but non-trivial.

I believe what you are thinking of is something else, namely defining a table in Python code, and then referring to that.
