### ISSUE TITLE
Datalab loses notebooks on crash

### ISSUE THREAD

**Issue by fhoffa** [googledatalab/datalab#672]
Today I created a couple notebooks, everything worked alright, and a couple hours later Datalab crashed.

After "reboot", the new notebooks I had created had disappeared without trace.

This is not the first time I have a notebook disappear. How can 'autosave' assure that they will not be lost on crash?

**Comment by gramster** [comment]
AFAIK we just use the normal Jupyter autosave mechanism here which is driven by a timer of ~ 2 minutes and then calls the same code as the explicit save path does. So this may be unrelated to autosave. Did you check the git workspace?

**Comment by fhoffa** [comment]
Unfortunately I haven't been able to reproduce it - but somehow it's not the first time one of my notebook disappear without trace (not even on the git workspace).

**Comment by qimingj** [comment]
There is a bug that when it fails to sync workspace, all subsequent sync will be blocked. I suspect that might be the case. I'll get the fix in soon.

We are also seeing an odd workspace sync failure after reboot or redeploy --- under investigation.

**Comment by yebrahim** [comment]
Closing this as obsolete. Please reopen if this still happens.

**Comment by MaxGhenis** [comment]
This may have just happened to me. I reconnected to my datalab instance (stopped the VM for a few days while I wasn't using it) and can view another notebook I created, but this tab URL had a notebook which was open earlier and now gives a 404:
https://8081-dot-3122383-dot-devshell.appspot.com/files/datalab/notebooks/UBISc.ipynb

I did have another Cloud project which I deleted, though I'm almost certain I created the now-missing notebook in the still-active project. The URL for the other notebook I still see has the same 3122383 element.

Happy to share more details about the cloud project if that could help debug.

**Comment by emilmahler** [comment]
This just happened to me. A crash and then all my files disappeared. I setup the DataLab just a couple of days ago, so I'm guessing all the versions are the latest.

**Comment by chmeyers** [comment]
emilmahler, a couple questions: were you using Cloud Shell?  Do you know what directory you were storing your notebooks in?  Did the automatic backup include the notebooks?
 (https://cloud.google.com/datalab/docs/how-to/working-with-notebooks#cloud_datalab_backup)
