### ISSUE TITLE
Time to time non responsive Datalab VM

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#739]
Often my Datalab is becoming non-responsive during execution of Python cell.
<img width="1436" alt="non_responsive" src="https://cloud.githubusercontent.com/assets/8209940/12131829/efa24590-b3ca-11e5-97b4-1522559f4031.png">

The only way I found to make it back to working state is to reset the VM (and reinstall again manually some Python packages), but this operation is taking ~20 minutes, which is less than optimal.

If you can detect this non-responsive state it will be great, as for now I have everything green in my monitoring console, but the reality is less than green. Especially if the user need to pay excessive CPU usage due to internal .

Any suggestion how to restart faster?

I hope you will be able to make it more stable, let me know if you need some access some logs to analyze the causes of this

**Comment by qimingj** [comment]
Some libraries, if used unexpectedly, may cause excessive resource usage including CPU, disk, memory. Can you isolate your code and find which part of code is consistently causing this?

We also have options to specify a more powerful VM (disk, memory, cpu) config during Datalab deployment. These options are supplied in URL of the deployer. For example:

http://datalab.cloud.google.com?cpu=2&memorygb=7.5&diskgb=200

By default the VM we choose is a standard one.

**Comment by VelizarVESSELINOV** [comment]
Thank for URL to increase resources, I will try with this and check if it is more stable. I didn't manage to identify direct correlation of code that is freezing the VM. The same code worked well before, and after the reset.
I have the feeling that it is linked several parallel executions or connection failed/restart notebook session...
The code I was executing was Python with pandas and Google BigQuery & Storage before the freeze.

**Comment by VelizarVESSELINOV** [comment]
App engine Datalab version issue
