### ISSUE TITLE
Multi-user collaborative Datalab

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#741]
Today Datalab is very single user focus, far away from the Google Docs interactive multi-user UX.

It is very difficult to know who is running Datalab which Notebook is running, no option to provide comments, etc.

I would suggest you to connect with your colleagues at Google involved in this project:
http://bids.berkeley.edu/resources/videos/jupyteripython-state-multi-user-and-real-time-collaboration

Jupyter Drive collaboration example: https://github.com/jupyter/jupyter-drive
Or the original CoLabotory project: http://colaboratory.jupyter.org/welcome/

**Comment by oliviernguyenquoc** [comment]
Google just released : Colaboratory
https://research.google.com/colaboratory

Can we hope an integration in Datalab in a near future ?

**Comment by nikhilk** [comment]
Thanks for the interest!

Yes, we're working on integrating more collaborative use-cases into the product. Closing this out, but will share more as we progress and are ready to share more broadly, esp. to on-board initial set of users.
