### ISSUE TITLE
How to stop Datalab using unnecessary resources?

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#742]
I deployed Datalab in more than one project, how I can stop consuming resources on the projects that I'm not actively using it.

I tried to stop the GAE Datalab instance, but somehow the instance is constantly starting to run and use cloud resources.

Suggestions:
1. Simplify the possible to put Datalab in off or standby mode
2. As any of the smart TV these days, add an automatic switch to standby mode after 1 hour of non usage

**Comment by nikhilk** [comment]
How did you try to stop? My guess is you tried stopping via the Compute Engine instances page. This will not work.

In Developer Console, click on AppEngine > Instances, and drill in into the datalab instance, you should see a Stop command at the top.

So far we haven't implemented auto-shutdown since you might have notebooks with running state you'd like to return to... it is however certainly interesting to consider.

Hope that helps.

**Comment by nehalecky** [comment]
> In Developer Console, click on AppEngine > Instances, and drill in into the datalab instance, you should see a Stop command at the top.

I've tried many different permutations of this sequence of finding the instance reference through App Engine, clicking a stop button at the top, watching it shut down and then, watching it come back to life a few minutes later. Scary.

Surely there is something I am missing—I suspect it shouldn't be this difficult?  I'd also like to free compute engine resources, so would appreciate any help, thanks.

**Comment by nikhilk** [comment]
Sorry for the trouble.

Please try App Engine > Versions > pick Datalab in the module picker > select the version (likely main) > click Delete.

Agree, this is more complex than needed, but fwiw, its documented here: https://cloud.google.com/datalab/getting-started#manage_instances_and_notebooks (look for "Deleting VM Instances")

**Comment by nehalecky** [comment]
@nikhilk, thanks for the clarification (and the link). Was able to finally turn off the instance, much appreciated.

To provide a little more context: I came across this thread initially, searching for *stop datalab instance*, assuming I simply wanted to shut down the service (but not deleted it). I should have taken the time to read through the documentation (which does seem quite helpful), but life in the fast lane to MVP. :fearful: 

Thanks again. :)

**Comment by mchirico** [comment]
I think the instructions are incorrect, and somewhat misleading  

>  https://cloud.google.com/datalab/getting-started#manage_instances_and_notebooks -- specifically the area with the comment "You may want to stop a Cloud Datalab managed VM instance to avoid incurring ongoing charges."  


Please confirm, but after stopping the instance for about 5 minutes,  long enough for the user to think it's stopped, it does appear to restart.  If confirmed, could you please change the documentation?

**Comment by Di-Ku** [comment]
@mchirico 
Absolutely. Checking into this again and of course, if confirmed, we will fix the docs.

**Comment by Di-Ku** [comment]
Yes, you are right. Submitted a doc fix. Should be live very soon.
https://cloud-dot-devsite.googleplex.com/datalab/getting-started#manage_instances_and_notebooks

Separately, App Engine Managed VM team is looking into Cloud Console user experience for stopping a version of a module.

**Comment by tglaser11** [comment]
This is extremely frustrating.  I cannot delete the datalab using the instructions above.  Keep getting error --
"Error: There is an operation pending for this application.  Please wait and try again."

I keep trying after a period of time...but doesn't work.  The charges to my account are growing and I cannot stop.

**Comment by AminaG** [comment]
I also also cannot delete datalab. What should I do?

**Comment by Di-Ku** [comment]
@tglaser11 and @AminaG 
First sorry about the error. There is a high pri bug for GAE Flex Runtime that is used by Datalab. 
Does stopping the instance work using 
$ gcloud auth login
$ gcloud config set project <YOUR PROJECT ID>
$ gcloud preview app versions start main

That should stop billing. The team is working on the delete error.

**Comment by smrgit** [comment]
I came upon this github issue and I have used the gcloud command specified above (earlier this morning).  Just to clarify -- athough this is described as "stopping" a Datalab instance, it is actually *deleting* the GCE VM and when I go back to datalab.cloud.google.com I have to do a new *deploy* rather than just click on "start".  (The App Engine version seems to still exist, but the underlying VM has definitely been deleted as far as I can tell, rather than just stopped.)

**Comment by chmeyers** [comment]
As this refers to the AppEngine version of Datalab, this issue is obsolete.

**Comment by VelizarVESSELINOV** [comment]
@chmeyers I think the problem is still open and even more valid, the VM will still turn forever if it is not closed, especially now that each user need to have dedicated VM

**Comment by nikhilk** [comment]
Agree, this is relevant... but might be better tracked as a feature request for automatic lifetime management without the history on the legacy implementation?

**Comment by chmeyers** [comment]
Created https://github.com/googledatalab/datalab/issues/1264 to track implementing VM lifetime management.
