### ISSUE TITLE
Check and fix any incorrect key bindings

### ISSUE THREAD

**Issue by gramster** [googledatalab/datalab#777]
Shift-J/K are documented as being used to navigate between cells but are not working (at least on a Mac).

We need to go through all the documented key bindings and check which ones don't work and fix them or the documentation.

**Comment by mchirico** [comment]
It's the Ctrl-J/K documentation that maybe incorrect, on the dropdown KeyBoard Shortcuts.  

<img width="312" alt="screenshot 2016-03-04 21 58 09" src="https://cloud.githubusercontent.com/assets/755710/13545280/9257c8fc-e254-11e5-9be1-ca944da6d313.png">
