### ISSUE TITLE
Rename gcp.stackdriver.monitoring to gcp.monitoring?

### ISSUE THREAD

**Issue by rimey** [googledatalab/datalab#807]
In #805, @nikhilk proposed changing `gcp.stackdriver.monitoring` to `gcp.stackdriver` or `gcp.monitoring` so the depth of the package hierarchy is consistent across `gcp`.

`gcp.stackdriver` is not really a viable option, because Stackdriver encompasses a number of products, of which Stackdriver Monitoring is just one.

I don't personally have a preference regarding `gcp.stackdriver.monitoring` (the status quo) versus `gcp.monitoring`.

**Comment by gramster** [comment]
Philosophical questiion - are any of the other parts of StackDriver likely to be incorporated into DataLab? Or are other monitoring approaches likely to be incorporated? If the former, the datalab.stackdriver might be the right  place. If the latter, perhaps datalab.monitoring.stackdriver?

**Comment by supriyagarg** [comment]
It would be the former - other parts of StackDriver (e.g. logging) will likely be incorporated into DataLab.
With the updated code structure, `datalab.stackdriver.monitoring` would be the new place for the monitoring code.

**Comment by ojarjur** [comment]
We finally settled on "google.datalab.stackdriver.monitoring".
