### ISSUE TITLE
Redirect not working correctly when datalab is installed on a remote server on first run

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#818]
I installed datalab on a server, then attempted to connect to it remotely.

After logging into datalab on the remote server with my Google credentials for the first time, I am incorrectly redirected to localhost (url http://localhost:8081/oauthcallback?state=/&code=4/XXXXXXXXX). I get the following error:

```
This site can’t be reached

localhost refused to connect.
Search Google for localhost 8081 oauth callback
```

I can successfully connect to Datalab on the remote server if I re-enter the correct ip. This issue only appears on the first run after authentication occurs.

**Comment by parthea** [comment]
I tried replacing the hard coded host `'http://localhost:8081/oauthcallback' ` in `auth.ts` with ` 'http://' + request.headers.host + '/oauthcallback'` but then I ran into a different error.

```
400. That’s an error.

Error: invalid_request

device_id and device_name are required for private IP: http://192.168.XX.XX:8081/oauthcallback

```

Its possible that redirecting to a private ip may not work for oauth.

http://stackoverflow.com/questions/22638427/hwioauthbundle-google-login-device-id-and-device-name-for-a-webapp
http://stackoverflow.com/questions/24736168/error-invalid-request-device-id-and-device-name-are-required-for-private-ip

**Comment by gramster** [comment]
It's possible that some of the workarounds mentioned here will help:
http://stackoverflow.com/questions/24736168/error-invalid-request-device-id-and-device-name-are-required-for-private-ip

**Comment by parthea** [comment]
Obsolete. Users should [run datalab locally](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local), although jupyter gateway can be local or remote
