### ISSUE TITLE
Try get files created in docker container to use user id of real (external) user

### ISSUE THREAD

**Issue by gramster** [googledatalab/datalab#836]
Right now they are created by the root user in the container which causes problems for files created on the externally mapped volume.

**Comment by gramster** [comment]
I haven't found a good solution to this. One idea I've seen which isn't portable is to change the numeric uid for root in the container to match the external user's uid. But that makes the container user-specific, and seems like it could break a bunch of things too.

There is a -u argument to docker run to specify the uid/gid to run as, but this means the user loses root permissions in the container and can't do things like apt-get etc. 

It does seem like the external user ID will be available through the /content owner in the container. So one could do something like this on startup:

    chown -R `stat -c "%u:%g" /content` /content

but that will only change existing files. We could also modify the node server and possibly the Jupyter kernel to change the ownership on newly created files to match that above. But files created in other ways (e.g. %bash magics) won't get this change. We could run the command above periodically to address that.

There is a setfacl command in Linux which would let us assign default permissions such that any files created in a directory would be readable/writable by a user/group, but I expect those ACLs are *nix specific and aren't going to help for access outside the container.

**Comment by ojarjur** [comment]
We are now only recommending the local run to people developing Datalab, so this is no longer an issue that we intend to address.
