### ISSUE TITLE
Release notes could be generated automatically

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#840]
Similar to how release notes are generated in [pandas](https://github.com/pydata/pandas/tree/master/doc#about-the-pandas-documentation), release notes could be generated automatically for Datalab using [Sphinx](http://www.sphinx-doc.org/en/stable/).

Other useful links:
[Docstring Standard](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#docstring-standard)
[First Steps with Sphinx](http://www.sphinx-doc.org/en/stable/tutorial.html#defining-document-structure)
[Documenting Your Project Using Sphinx](https://pythonhosted.org/an_example_pypi_project/sphinx.html)

There a bit of initial work up front (and changes to the development process), but I think it will save time for developers in the long run. Release notes regarding bug fixes/featues could be added as part of each commit (if required). Updates to the release notes could be included as part of the code review. See the [source](https://github.com/pydata/pandas/blob/master/doc/source/whatsnew/v0.18.2.txt) for pandas release notes 0.18.2. This file is updated very frequently during the development cycle. 

An added benefit would be to add the github issue number so users can view the specific source code changes for the corresponding bug or feature in the release notes.

**Comment by VelizarVESSELINOV** [comment]
👍 In general, the release notes, what it is new in each version are not well managed. At least it is unclear for me what it is content of the latest package. GitHub proposes nice release management https://github.com/GoogleCloudPlatform/datalab/releases, but it is not updated. The wiki it is also obsolete: https://github.com/GoogleCloudPlatform/datalab/wiki.

**Comment by parthea** [comment]
@ojarjur  In an effort to help with cleaning up open issues, here is a bit more detail about this feature request.

My initial thought was that the Google Datalab release notes could be part of the development process and encouraged during code review process.  For example, see the release notes for pandas and corresponding html file: https://github.com/pandas-dev/pandas/blob/master/doc/source/whatsnew/v0.20.0.txt and
http://pandas.pydata.org/pandas-docs/stable/whatsnew.html . 

If release notes are generated automatically when creating the Datalab docs then potentially the [Release Info Wiki Page](https://github.com/googledatalab/datalab/wiki/Release-Info) could be deprecated .

In terms of the [Release Info Wiki Page](https://github.com/googledatalab/datalab/wiki/Release-Info), I noticed that the fixes for the `google.datalab` library are included in the release notes of Cloud Datalab.  One idea is to have separate release notes for Cloud Datalab and the `google.datalab` library.  The release notes for Cloud Datalab could reference the version and release notes of the `google.datalab`  library. 

Let me know if this is something that could be helpful and I can submit a PR to move this forward. Otherwise, ok to close.

**Comment by yebrahim** [comment]
I think this makes sense for the release notes to go into the releases page, although I'm not sure how to automate this process. Perhaps it's sufficient to just manually do `git log ...` since last release to get the list of commits and list them in the release notes.

**Comment by parthea** [comment]
Closing as obsolete.
