### ISSUE TITLE
Move to pandas 0.18.1

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#844]
Please upgrade pandas to 0.18.1

```
pip install -U pandas==0.18.0 && \
```

**Comment by parthea** [comment]
Using gcr.io/cloud-datalab/datalab:local ,

```
> import pandas
> pandas.__version__
u'0.18.1'
```

0.18.1 is the [latest release](http://pandas.pydata.org/pandas-docs/stable/release.html) for pandas, and is currently in the latest datalab image.

@ojarjur Can we close this one?

**Comment by VelizarVESSELINOV** [comment]
Yes, tnx :)
