### ISSUE TITLE
Warning message in console when running Datalab locally

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#845]
When I run Datalab locally, I see the following warning in the console.

```
{"name":"app","hostname":"XXXXXX","pid":20,"type":"jupyter","level":30,"msg":"[9000]: Message signing is disabled.  This is insecure and not recommended!\n","time":"2016-05-15T19:32:38.335Z","v":0}
```

This is most likely related to the following issue: https://github.com/jupyter/qtconsole/issues/119 . There is a patch in IPython Kernel 4.3.2

**Comment by yebrahim** [comment]
This doesn't look like it ever got fixed, but I think we can close this as no-op for Datalab.
