### ISSUE TITLE
Datalab Tree not correctly sync with Google Cloud Source Repository

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#865]
It is not the first time that Google Cloud Developemt (Source Code) is not sync with Datalab Tree, please make it more stable. In some cases was the issue with Source Code (not able to sync), but several times we lost our new files in the Datalab Tree and we found them in Source Code not committed version available.

**Comment by LoveRose90** [comment]
V0 PLEASE

**Comment by josecelaya** [comment]
I have same issue. No information on how to solve online beside giving up on GCP git and do some other solution.

**Comment by HMarkovic** [comment]
I am having similar issue that sounds more scary:
- I could see uncommitted file changes by a different user as my modifications (other user is sitting in room next to me so I could check)
- I could not commit anything, getting a message that I am behind HEAD but could not refresh
- I tried after 5 min and I could commit all: both my changes and other user changes (nothing was refreshed though)

**Comment by VelizarVESSELINOV** [comment]
Obsolete issue
