### ISSUE TITLE
Please do not deprecate datalab.cloud.google.com

### ISSUE THREAD

**Issue by jaycode** [googledatalab/datalab#873]
I'm referring to [this readme](https://github.com/GoogleCloudPlatform/datalab/wiki/Getting-Started):

> The easiest way to use Google Cloud DataLab is on Google Cloud Platform. Head over the DataLab site, and deploy an instance into a Cloud Project. Note that this way is being deprecated though in favor of using Datalab locally or on your own GCE instance, as described below.

Please do not deprecate https://datalab.cloud.google.com. It is very helpful for users who need quick setup before starting the actual work on their projects, just like me.

On another note, is it possible to update the datalab version there? For some reason I cannot use module `datalab` in my notebook environment. More detail is shown in [the comments of this stackoverflow post](http://stackoverflow.com/questions/37631204/google-bigquery-invalid-source-format-csv-when-loading-data-from-datalab/37632182#37632182).

Thank you.

**Comment by parthea** [comment]
https://datalab.cloud.google.com has already been deprecated in favor of the local setup. It is easy/quick to get datalab running locally. The link to the quick start guide can be found [here](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local). Datalab is up-to-date in the local installation. If you find the experience is not easy/quick, please post your experience here.

Ok to close this issue?

**Comment by andrewverte** [comment]
@parthea Slightly related, but can you release the scripts that built the app engine flexible services? There are some advantages to running datalab in GAE Flexible over GCE.

**Comment by ojarjur** [comment]
@andrewverte The code for the Docker image of the previous version is already released under the 'datalab-managed' branch, and the image currently tagged "gcr.io/cloud-datalab/datalab:latest" is the latest build of that branch (although we may reclaim that tag for the local version at some point in the future).

I just verified that it can be deployed by creating two files named "Dockerfile" and "app.yaml" (in an otherwise empty directory) and then running 'gcloud app deploy ./app.yaml --project ${PROJECT_ID}'. That is roughly what the old deployer did.

However, be forewarned that we won't be able to provide any support for this use case.

In case you want to try it yourself, the contents of the two files for deployment should be:

Dockerfile:

    FROM gcr.io/cloud-datalab/datalab:latest

app.yaml:

    service: deprecated-datalab
    api_version: 1
    vm: true
    runtime: custom

    manual_scaling:
      instances: 1

    network:
      name: datalab

    health_check:
      enable_health_check: false

    handlers:
    - url: /.*
      script: app.js
      login: admin
      secure: always

**Comment by andrewverte** [comment]
@ojarjur Thank you for the quick and informative reply!

**Comment by parthea** [comment]
@ojarjur I believe this issue is resolved (responded). If there is no action item, can we close this issue?

**Comment by Di-Ku** [comment]
@jaycode We hear you but we are sorry that is just not feasible. Deployer is not hard to keep but the Datalab version it deploys has some dependencies (e.g. Commit UI in Cloud Console) that are not going to be continued going forward. Ergo, the old version will at some point become very hard to use or unusable. At that point, we won't have a persistence manager that makes sense with a pure cloud-based Datalab. Plus we have made significant enough changes that the old version is anyway not sustainable with the resources we have.
We are working on a much better story for v_next but local containers is currently our best bet for V1 given various constraints and dependencies. Meanwhile we are also working on sending out the appropriate communication via official channels. So this is quick heads up.
