### ISSUE TITLE
Executing script created server side 'crash', NGINX error and after that lost the file

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#881]
As we already mentioned before time to time we have crashes and we are loosing files.

Sequence of events:

1. Save copy of the file (Y)
2. Work on the copy and save it
3. Commit the copy (Y)
4. Work again on the file (Y) trying to display higher resolution data
5. Not responding for a few minutes
6. NGINX error after a few minutes: #878 
7. Page 404 error after a few seconds
8. Go back to Datalab tree and the file (Y) is missing
9. Source Repo is proposing me to commit the edits of the new created file

Conclusion: Datalab code is descychronized with Code Source Repository and looks like Cloud Source Repository has the correct version of code and Datalab is back to previous version of the code

Please find a collection of some error messages that maybe will help you to understand the root cause of the issue:
Several server and client errors
![image](https://cloud.githubusercontent.com/assets/8209940/16255078/2567a38c-37fb-11e6-9813-8b611bebc243.png)

![image](https://cloud.githubusercontent.com/assets/8209940/16255106/744603e0-37fb-11e6-9a4a-e09c7e7e90cf.png)

Serial console output of the VM (most of the errors looks older than 10PM PST):
fsck: fsck.ext4: not found
fsck: error 2 while executing fsck.ext4 for /dev/sda1
fsck died with exit status 8
done.
Warning: File system check failed but did not detect errors
[    1.808185] tsc: Refined TSC clocksource calibration: 2300.003 MHz
...
Jun 21 20:54:06 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:06 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
Jun 21 20:54:08 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:08 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
Jun 21 20:54:10 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:10 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
Jun 21 20:54:12 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:12 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
Jun 21 20:54:14 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:14 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
Jun 21 20:54:16 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:16 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
Jun 21 20:54:18 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:18 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
Jun 21 20:54:21 vm_runtime_init: ah_start: INFO: app container running
Jun 21 20:54:21 vm_runtime_init: ah_start: app not healthy, won't send /_ah/start yet.
gcm-Heartbeat:1466542462000
Jun 21 20:54:23 vm_runtime_init: ah_start: WARNING: never got healthy response  from app, but sending /_ah/start query anyway.
Jun 21 20:54:23 vm_runtime_init: Done start 'ah_start'.
...
gcm-Heartbeat:1466563254000
gcm-StatusUpdate:TIME=1466542463000;STATUS=ALL_COMMANDS_SUCCEEDED
[20999.597228] aufs may_rename_srcdir:471:pip[22393]: renaming dir who has child(ren) on multiple branches, is not supported
Jun 22 02:41:08 gae-datalab-main-XXXX kernel: [20999.597228] aufs may_rename_srcdir:471:pip[22393]: renaming dir who has child(ren) on multiple branches, is not supported
gcm-Heartbeat:1466563284000
gcm-StatusUpdate:TIME=1466542463000;STATUS=ALL_COMMANDS_SUCCEEDED

**Comment by ojarjur** [comment]
First off, thanks for the report.

The nginx error messages lead me to believe that the Managed VM was replaced (which should happen about once per week). If you look in the "Compute Engine > Operations" section of the Cloud Console, do you see three operations around that time saying "Stop an instance", "Delete an instance", "Create an instance", where all three have the same instance name?

If so, then that might help us figure out where the source of the bug could be.

**Comment by VelizarVESSELINOV** [comment]
Same issue today, I managed to resync Datalab with Source Code, after series of actions: Google Source Code commit, git pull, git push, git reset --hard origin/datalab_main, etc.

**Comment by ojarjur** [comment]
> Same issue today, I managed to resync Datalab with Source Code, after series of actions: Google Source Code commit, git pull, git push, git reset --hard origin/datalab_main, etc.

Are there Compute Engine operations from that time showing the VM being deleted and recreated? Knowing that will help us narrow down the potential sources of the problem.

**Comment by VelizarVESSELINOV** [comment]
No events recorded during 24 June in the Computer Engine operations log.

The instance was "terminated during maintenance" on  22 June, 21 June, 19 June and 17 June. Is it normal that almost each two day maintenance is done?

**Comment by ojarjur** [comment]
> No events recorded during 24 June in the Computer Engine operations log.

Thanks for checking; that disproves the theory I was working under, so it should save us a lot of time debugging.

> The instance was "terminated during maintenance" on 22 June, 21 June, 19 June and 17 June. Is it normal that almost each two day maintenance is done?

I don't know if that is normal or not, but it also doesn't seem to be related to the issue you saw (and it wasn't causing other issues, right?).

Jose mentioned in [another issue](https://github.com/GoogleCloudPlatform/datalab/issues/884) that this may be due to the wrong workspace being opened. That's seems like a more promising theory than anything I was able to come up with, so I'll start digging into that one and hopefully the two issues will turn out to be the same.

**Comment by VelizarVESSELINOV** [comment]
App engine issue
