### ISSUE TITLE
Faster VM start

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#888]
Today start a Datalab VM is taking 31 minutes, is it possible to make it faster?

**Comment by VelizarVESSELINOV** [comment]
Deployment of new version of Datalab was done faster (~10 min) than start/stop yesterday.

**Comment by ojarjur** [comment]
Did the slow start that you saw coincide with [this incident](https://status.cloud.google.com/incident/compute/16012)?

If so, then maybe that was the issue.

**Comment by VelizarVESSELINOV** [comment]
App engine issue, closing
