### ISSUE TITLE
UX: Responsive design

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#889]
On small screen there are a lot of challenges (laptop with debugging window open use case):
1. The main action menu is not visible
2. A lot of space is used for nothing on the right side, it will be nice to be optional
3. There are big offset which is maybe good for big screens, but for small screen it is not very useful

![image](https://cloud.githubusercontent.com/assets/8209940/16494728/3ef8137c-3e9f-11e6-9e9a-40692ec178b9.png)

Jupyter online is more usable even in a smaller screen:
![image](https://cloud.githubusercontent.com/assets/8209940/16494526/85f6a384-3e9e-11e6-9c65-8002d3c91b08.png)

**Comment by yebrahim** [comment]
Fixed by https://github.com/googledatalab/datalab/pull/1235.
