### ISSUE TITLE
Uploading large files fails

### ISSUE THREAD

**Issue by dsignr** [googledatalab/datalab#903]
When trying to upload large files, there is no progress bar displayed and then in the middle of the process, the browser window crashes.

Chrome Version 51.0.2704.103 (64-bit), on OS X El Captain

**Comment by archelogos** [comment]
Yep I'm experiencing the same when trying to upload .pickle, .mat or .gz files

Similar Chrome version and same OS

**Comment by yebrahim** [comment]
Closing as dup of https://github.com/googledatalab/datalab/issues/1324. See the conversation there.
