### ISSUE TITLE
Script or REST call to fast deploy multiple datalab instances on GCP

### ISSUE THREAD

**Issue by josecelaya** [googledatalab/datalab#911]
The current tool for datalab deployment is quire rudimentary. Is there a way, script, REST call on a script or other, where I can deploy 20-30 datalab engines without having to do it one by one typing the URL and following the remainder part of the wizard. 

My project reached the point where I need to have 20-30 people using datalab, training a machine learning algorithm and having heavy use of PANDAS. No way this can work on a single datalab app engine set up with one VM instance. I have no way to set up also an instance group to share the load but this could be an option 2. 

I am okay creating different app engine deployments of datalab (additional versions under the datalab service). I just need to share a different URL for each user or two. Also, I do not want the users to be able to do their own deployment since the current deployment method is quite finicky and it is very easy to break the datalab_main version of the service. 

@ojarjur is this possible?

**Comment by ojarjur** [comment]
Unfortunately, no; we don't have a way of doing that.

For now the best solution we can provide is to increase the machine size (using the "cpu" and "memorygb" URL parameters), so that you can minimize the number of instances you have to create.

**Comment by yebrahim** [comment]
Closing this as we now have the CLI script to create Datalab instances.
