### ISSUE TITLE
Error: '/datalab/run.sh' not found or does not exist when running datalab locally

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#915]
After pulling the latest master, I receive an error when trying to run datalab locally.

```
>> ./run.sh
./run.sh: 40: [: unexpected operator
docker: Error response from daemon: Container command '/datalab/run.sh' not found or does not exist..
```

Based on the following instructions:
https://github.com/googledatalab/datalab/wiki/Getting-Started

The datalab folder in the container does not have a `run.sh` script
```
>> root@77835d2023ce:/datalab# ls
lib  nbconvert
```

**Comment by ojarjur** [comment]
I'm not able to reproduce this yet. Can you give me some more details?:

- Are you running this under Linux, Mac OSX, or something else?
- Were there any errors from running the "containers/datalab/build.sh" script?  In particular, is there a line that says "Step 1 : FROM datalab-base" followed later by a line that says "Successfully built ..." ?

**Comment by parthea** [comment]
- I'm running Ubuntu 14.04
- I didn't see any errors in the output of the "containers/datalab/build.sh" script

I noticed the following
`/build.sh: 31: ./build.sh: pushd: not found`


```
./build.sh 
sending incremental file list
created directory build
./
build.log
web/
web/app.js
web/auth.js
web/callbacks.js
web/health.js
web/httpapi.js
web/info.js
web/jupyter.js
web/logging.js
web/package.json
web/server.js
web/settings.js
web/static.js
web/userManager.js
web/config/
web/config/settings.json
web/static/
web/static/datalab.css
web/static/datalab.ico
web/static/datalab.js
web/static/datalab.png
web/static/datalab.txt
web/static/eula.html
web/templates/
web/templates/edit.html
web/templates/nb.html
web/templates/sessions.html
web/templates/tree.html

sent 144,558 bytes  received 554 bytes  290,224.00 bytes/sec
total size is 142,677  speedup is 0.98
./build.sh: 31: ./build.sh: pushd: not found
Sending build context to Docker daemon 17.41 kB
Step 1 : FROM debian:jessie
 ---> xxxxxxx
Step 2 : MAINTAINER Google Cloud DataLab
 ---> Using cache
 ---> xxxxxxx
...
...
Successfully built ....
```

I think a good next step is to try deleting all my docker images so there is no cache, then run `./build.sh` again. I'll post the results here

**Comment by ojarjur** [comment]
> /build.sh: 31: ./build.sh: pushd: not found

The `pushd` command failing will prevent this from working out of the box. What the script is trying to do at that point is to build the base image `datalab-base`, which is in another directory, and then switch back to building the main image.

Using `pushd`/`popd` for that directory traversal is probably unnecessary, so I've switched the scripts to just using `cd` and pushed out a commit with that change.

Can you try checking out the branch 'ojarjur/remove-pushd-popd-dependency' and see if it fixes the problem for you?

**Comment by parthea** [comment]
Thanks Omar! My issue is resolved after checking out branch 'ojarjur/remove-pushd-popd-dependency' 

Note:  I noticed `Step 1 : FROM debian:jessie` instead of `Step 1 : FROM datalab-base` 

```
>> ./build.sh
sending incremental file list
./
build.log
web/
web/app.js
web/auth.js
web/callbacks.js
web/health.js
web/httpapi.js
web/info.js
web/jupyter.js
web/logging.js
web/server.js
web/settings.js
web/static.js
web/userManager.js

sent 58,003 bytes  received 277 bytes  38,853.33 bytes/sec
total size is 142,677  speedup is 2.45
Sending build context to Docker daemon 17.41 kB
Step 1 : FROM debian:jessie
 ---> xxxxxxxxxxxx
Step 2 : MAINTAINER Google Cloud DataLab
 ---> Using cache
 ---> xxxxxxxxxxxx
...
...
Successfully built xxxxxx
```

**Comment by ojarjur** [comment]
> Note: I noticed Step 1 : FROM debian:jessie instead of Step 1 : FROM datalab-base

You should see both "FROM debian:jessie" and "FROM datalab-base", as the build process is actually producing two images now (i.e. the base for "datalab-base" is "debian:jessie").
