### ISSUE TITLE
Need to get the update notification working for local run Datalab

### ISSUE THREAD

**Issue by qimingj** [googledatalab/datalab#918]
- Create a version_check_local.js
- Change the notification link from Datalab deployer link to local run document.

**Comment by parthea** [comment]
Should updates happen automatically when datalab is run locally?

For example,

In the [quickstart doc](https://cloud.google.com/datalab/docs/quickstarts/quickstart-local) change
```
docker run -it -p "127.0.0.1:8081:8080" -v "${HOME}:/content"    -e "PROJECT_ID=<PROJECT>"    gcr.io/cloud-datalab/datalab:local
```
to
```
docker pull gcr.io/cloud-datalab/datalab:local && docker run -it -p "127.0.0.1:8081:8080" -v "${HOME}:/content"    -e "PROJECT_ID=<PROJECT>"    gcr.io/cloud-datalab/datalab:local
```

Alternatively, if manual updates are preferred, provide users with instructions on how to get the latest version on the [release info page](https://github.com/googledatalab/datalab/wiki/Release-Info). Users need to run `docker pull gcr.io/cloud-datalab/datalab:local`

**Comment by parthea** [comment]
@ojarjur The notification link is working in the local run. Can this issue be closed?

**Comment by ojarjur** [comment]
@parthea You are right; I forgot to close this when I verified things worked.

Sorry about that, and thanks for catching it.
