### ISSUE TITLE
Doing a chart map send an error

### ISSUE THREAD

**Issue by Cecitux** [googledatalab/datalab#920]
Hi

I am trying to do a chart map in Data Lab using data from Big Query, however send me an error and do not show the map. First i think that was an error with javascript but I try also using Internet Explorer and the result was the same. I attach the image with the error. 

This is the error

**# Cannot read property 'addEventListener' of undefined**

![image](https://cloud.githubusercontent.com/assets/16903090/17073447/94c22506-5036-11e6-9da5-3ab52bbc19ac.png)

**Comment by yebrahim** [comment]
This shouldn't happen anymore. Please reopen this issue if it repro's.
