### ISSUE TITLE
Require users to sign in, or display a warning message when not signed in

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#945]
Would there be a use case for using the datalab user interface without signing in? If not , is it possible to enforce sign in at startup of datalab, or when user is not signed in? 

I believe this would improve the login/logout experience. For example, when a user clicks `'logout'` they could be redirected to the datalab login page where they will be asked to login to continue. Alternatively, a warning message could be displayed so that the user knows that certain functionality may be limited.

See the following comment below on related issue where users could have an improved experience when using pandas inside datalab .

From pydata/pandas#13608,

>I also found that Pandas GBQ integration now works seamlessly in Google Datalab with this PR.
>
>Note: This only works if user is already logged into Google Datalab. One observation that I noticed is >that Google Datalab usually prompts the user to sign in if >oauth2client.client.GoogleCredentials.get_application_default() fails, but in this case the exception is >hidden in pandas, so user may not know that they need to sign in to Datalab in order to avoid the >additional sign in process for pandas.

**Comment by ojarjur** [comment]
> Would there be a use case for using the datalab user interface without signing in?

Yes there is. We want people to be able to use the locally installed version of Datalab without even needing to have a Google account, let alone being signed in with one.

For example, using Datalab with Tensorflow can be a good way to learn Tensorflow, and that should be an option for everyone regardless of whether or not they have a Google account.

**Comment by parthea** [comment]
Makes sense. Thanks for the explanation @ojarjur ! Closing this issue.
