### ISSUE TITLE
Auto Complete Window Disappears on Mouse click.

### ISSUE THREAD

**Issue by qimingj** [googledatalab/datalab#955]
Reproduce steps:

Run cell 1:

from gcloud import logging

On cell 2.
type:
logging.
and press tab. the list of available members appear. But on clicking any of them, the window disappears and it does not auto complete the typing.

**Comment by yebrahim** [comment]
This is an inherited behavior from Jupyter. They [finally fixed](https://github.com/jupyter/notebook/pull/1549/files) it in Jupyter 5.0, but that's not out yet. Closing this since there isn't much we can do here.
