### ISSUE TITLE
Cannot easily tell the difference between a code cell and a markdown cell

### ISSUE THREAD

**Issue by qimingj** [googledatalab/datalab#956]
We can probably change the cell UI a little bit to make them more different from each other.

**Comment by yebrahim** [comment]
Currently code cells have a slightly darker background color and a monospace font, I think the difference is clear. How do you think we can differentiate it more?

![image](https://cloud.githubusercontent.com/assets/1424661/19401633/385e7aea-9211-11e6-9200-4656f0c11a79.png)

**Comment by yebrahim** [comment]
@qimingj do you still feel we should do something here or can we close this?

**Comment by qimingj** [comment]
Let's close this. I am fine with the color difference.
