### ISSUE TITLE
socket.io.js results in 404

### ISSUE THREAD

**Issue by qimingj** [googledatalab/datalab#984]
https://github.com/googledatalab/datalab/blob/master/sources/web/datalab/templates/nb.html#L247 references /socket.io/socket.io.js but if socket is not enabled in web server, it results in 404 error.

Perhaps the reference to /socket.io/socket.io.js needs to be conditional. If possible, move socket.io.js into shim block (https://github.com/googledatalab/datalab/blob/master/sources/web/datalab/templates/nb.html#L270) in the require config and only enable it when needed in datalab.js.

**Comment by yebrahim** [comment]
I think this should've been fixed by https://github.com/googledatalab/datalab/pull/1120, can we test it?

**Comment by ojarjur** [comment]
@yebrahim Yes, it was. I just missed closing this bug.
