### ISSUE TITLE
Line magic commands silently fail if they are the first line in a cell, and cell body is not empty

### ISSUE THREAD

**Issue by parthea** [googledatalab/datalab#996]
I noticed the following error in the Datalab console when using the `%storage` line magic command.

```
{"name":"app","hostname":"b86c9881eefb","pid":89,"type":"jupyter","level":30,"msg":"[9000]: ERROR:root:Cell magic `%%storage` not found (But line magic `%storage` exists, did you mean that instead?).\n","time":"2016-09-26T11:35:28.505Z","v":0}
```

The error appears in the console when the following code is executed, in an otherwise empty cell:

```
%storage read --object gs://cloud-datalab-samples/cars.csv --variable cars
print(cars)
```

Using a new cell, I can confirm that `cars` is not defined

```
>print(cars)
NameErrorTraceback (most recent call last)
<ipython-input-16-b33add6e2bbd> in <module>()
----> 1 print cars

NameError: name 'cars' is not defined
```

The code works as expected if I put `%storage` on the second line (first line can be empty, comment, or python code). For example, 

```
# This comment is here to work around the issue where %storage doesn't work if it is the first line in a cell. 
%storage read --object gs://cloud-datalab-samples/cars.csv --variable cars
print(cars)
```

The output is correctly shown as:

```
Year,Make,Model,Description,Price
1997,Ford,E350,"ac, abs, moon",3000.00
1999,Chevy,"Venture Extended Edition","",4900.00
1999,Chevy,"Venture Extended Edition",Very Large,5000.00
1996,Jeep,Grand Cherokee,"MUST SELL! air, moon roof, loaded",4799.00
```

**Comment by parthea** [comment]
I'm going to submit a PR for this.

**Comment by parthea** [comment]
This issue also exists in the `google.datalab` package

**Comment by alexgorbachev** [comment]
I can confirm that the same behavior is with %matplotlib on the first line.

**Comment by nathanzhang3** [comment]
UsageError: Cell magic `%%matplotlib` not found (But line magic `%matplotlib` exists, did you mean that instead?).

**Comment by parthea** [comment]
Closing as obsolete.
