### ISSUE TITLE
File name not anymore displayed in the header

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [googledatalab/datalab#998]
Datalab [Version: 0.5.20160929]

**Comment by yebrahim** [comment]
Can you share more details? It's working fine on my Mac. A screenshot would be great too.

**Comment by VelizarVESSELINOV** [comment]
Chrome [Version 53.0.2785.143 (64-bit)] missing in the header file name and file status on macOS Sierra 10.12:
![image](https://cloud.githubusercontent.com/assets/8209940/18977835/c8ca2200-8672-11e6-8256-1f11183cf14b.png)

With console log:
![image](https://cloud.githubusercontent.com/assets/8209940/18977985/e3df8390-8673-11e6-9a8b-9b7f19f296ed.png)

**Comment by ojarjur** [comment]
Thanks for the report!

I can reproduce this; it's definitely a bug and I'll figure how to get it fixed.

**Comment by qimingj** [comment]
I opened an issue several days ago about socket.io.js 404: https://github.com/googledatalab/datalab/issues/984

The widget file missing is probably because we fail to enable widgets in Jupyter.

**Comment by ojarjur** [comment]
@qimingj I think the errors in the console log are a red herring, but I'll know more once I narrow down which change introduced the issue.
